### ISSUE TITLE
wrong parsing of mailto-links

### ISSUE THREAD

**Issue by mash-graz** [lepture/mistune#103]
email addresses including dots or dashes are not recognized as mailto links:

` mistune.markdown('mailto parser test: <email@nowhere.org>, <my.email@nowhere.org>, <my-email@nowhere.org>')`

will generate:

`<p>mailto parser test: <a href="mailto:email@nowhere.org">email@nowhere.org</a>, &lt;my.email@nowhere.org&gt;, &lt;my-email@nowhere.org&gt;</p>\n'`

only addresses of the first form work.

**Comment by lepture** [comment]
@mash-graz The master branch works fine.
