### ISSUE TITLE
Render Tables with Borders

### ISSUE THREAD

**Issue by rdsalemi** [lepture/mistune#107]
Hi,

Is there a simple way to render tables with borders around the cells?

Thanks!
Ray

**Comment by NPrescott** [comment]
Not specific to Mistune but the simplest way is to style the rendered HTML with CSS, for example:

```css
td { border: 1px solid black; }
```

Because HTML is valid markdown you could include an inline style element in your markdown document:

```
|       |     |
--------|------
 item 1 |  a
 item 2 |  b

<style>
td { border: 1px solid black; }
</style>
```

**Comment by rdsalemi** [comment]
Interesting. I wonder if it is possible to have that code automatically
placed in all HTML files.

**Comment by lepture** [comment]
It is not related with this library. Use CSS.
