### ISSUE TITLE
Re-Enable HTML data URLs

### ISSUE THREAD

**Issue by mitsuhiko** [lepture/mistune#109]
The current code blacklists text/html data URLs. They are very useful and there is no security problem with them because they execute in their own dom context. Can they be enabled again?

**Comment by lepture** [comment]
It is dangerous in Firefox. I'll disable it when it is not in `escape` option.

**Comment by mitsuhiko** [comment]
@lepture i cannot reproduce that. Firefox creates a new DOM context.
