### ISSUE TITLE
RecursionError on nested quotes

### ISSUE THREAD

**Issue by nitely** [lepture/mistune#114]
Not actually unique to quotes but also to lists and footnotes. The following code raises a `RecursionError`:

``` python
mistune.markdown('* ' * 1000 + ' a')
```

``` python
mistune.markdown('> ' * 1000)
```

Relevant discussion: https://github.com/thephpleague/commonmark/issues/243

**Comment by lepture** [comment]
@nitely Thanks for your report. This is solved in mistune-0.8, try the code in branch mistune-0.8
