### ISSUE TITLE
BlockLexer.parse is persistent

### ISSUE THREAD

**Issue by aisbaa** [lepture/mistune#116]
Hi, thank you for sharing your work, find it really useful. One thing I've noticed playing around is that `BlockLexer.parse` method is kind of persistent. If `parse` gets called twice with same data - it returns different results. So the question - was it intentional?

```
>>> lexer = mistune.BlockLexer()
>>> text = """
... # h1
... 
... lorem ipsum
... """
>>> lexer.parse(text)
[{'text': 'h1', 'type': 'heading', 'level': 1}, {'text': 'lorem ipsum', 'type': 'paragraph'}]
>>> lexer.parse(text)
[{'text': 'h1', 'type': 'heading', 'level': 1}, {'text': 'lorem ipsum', 'type': 'paragraph'}, {'text': 'h1', 'type': 'heading', 'level': 1}, {'text': 'lorem ipsum', 'type': 'paragraph'}]
>>> mistune.__version__
'0.7.3'
```

**Comment by lepture** [comment]
You can see that the second result is a duplicated version of the first one. The result is kept in a list with `push`.

**Comment by aisbaa** [comment]
Thank you for your answer, I'll assume that this is intentional behavior.
