### ISSUE TITLE
Feature request - use mistune on the command line

### ISSUE THREAD

**Issue by davidwtbuxton** [lepture/mistune#121]
Hello,

I'd like to add support for mistune to be called on the command line to transform markdown to html.

The simplest case would be to add support for mistune to be called as a module to process markdown from stdin and emit html to stdout. Example of proposed usage:

    $ python -m mistune < in.md > out.html

This would be equivalent to the following script:

    import sys
    import mistune

    src_text = sys.stdin.read()
    dest_text = mistune.markdown(src_text)
    sys.stdout.write(dest_text)

I am guessing we would probably assume utf-8 for input and output, and potentially we would need to decode / encode text as necessary.

A more advanced feature would include support for passing flags to change the rendering behaviour, e.g. `python -m mistune --use-xhtml --hard-wrap < in.md > out.html`, and accepting positional arguments for the source / destination file names. But that can be ignored for a first attempt.

Good idea? Would a pull request be considered?

Thanks for mistune,

David B.

**Comment by lepture** [comment]
Hi @davidwtbuxton 

I'd keep this repo as a pure library. You may create a `mistune-cli` repo which exposes a command line tool.
