### ISSUE TITLE
Non-breaking spaces silently converted to regular spaces

### ISSUE THREAD

**Issue by encukou** [lepture/mistune#125]
Hello!

I have content with Unicode non-breaking spaces (`\u00a0`) at the correct places.
I noticed that Mistune [silently converts these to regular spaces](https://github.com/lepture/mistune/blob/master/mistune.py#L87). Neither Github nor python-markdown do this.

Is this a deliberate feature?
Would you accept a patch to remove it, or make it optional?

(Background: In Czech, non-breaking spaces are quite common: certain one-letter prepositions bind so tightly to the following word that it's considered bad form to break the line after them. I have a lot of content with non-breaking spaces, and using `&nbsp;` instead would make it quite unreadable.)

**Comment by lepture** [comment]
I believe it is not a feature. I'll remove it.
