### ISSUE TITLE
parse_block_html with hard_wrap=True

### ISSUE THREAD

**Issue by madjxatw** [lepture/mistune#133]
When setting both `parse_blcok_html` and `hard_wrap` to True,  each html line will be appended with a `<br>` except the last line.

Input:
```
<div class="test">
<p>test1</p>
test 2
<p>test3</p>
</div>
```
Output:
```
<div class="test"><br>
<p>test 1</p><br>
test 2<br>
<p>test 3</p></div>
```

**Comment by idnsunset** [comment]
Same issue here, trailing <br> for each html line when set hard_wrap to True.

**Comment by lepture** [comment]
I think it is the right behavior.

** parse_block_html** means that mistune won't treat content in the block as HTML, instead the content is treated as text.

**hard_wrap** means that every newline should be a linebreak.

Together, current behavior is the right behavior.

**Comment by madjxatw** [comment]
As my understanding, `parse_block_html` means parsing the markdown text within a HTML block, in other words, if `parse_block_html` is not set, mistune will ignore the markdown text within a HTML block. A simple example:

```html
<div>
<p>text</p>
**bold text 1**
**bold text 2**
</div>
```
if `parse_block_html` is set, `**bold text**` will be converted to `<strong>bold text</strong>`, **but the raw html  `<p>text<p>` won't be touched**.  And if `hard_warp` is **not** set, we need 2 trailing spaces after `bold text 1` to make `bold text 2` a new line.

Maybe I misunderstood, please advice, thanks.

**Comment by lepture** [comment]
@madjxatw that is too complex. Currently, mistune treat everything in a whole in `<div>`, including `<p>`.

**Comment by madjxatw** [comment]
That's all right, this is actually not a issue although other markdown-html converter like pandoc can handle such case,  I could write script to clean the html.
