### ISSUE TITLE
Code block with 4 leading spaces

### ISSUE THREAD

**Issue by madjxatw** [lepture/mistune#135]
When I put  a code block with 4 leading spaces, then a blank line below and start a new paragraph. 
```
    4 leading spaces and my code here

new parapraph
```
I found  the blank line is also wrapped into `<pre><code>` tags which is not correct. 
```html
<pre><code>4 leading spaces and my code

 </code></pre><p>new paragraph</p>
```
As my understanding, the blank line is intended to tell where the code block should ends but not the part of code block, isn't it?

**Comment by lepture** [comment]
Hi @madjxatw 

I've tested it on my local machine, it works perfect. The result is:

```html
<pre><code>4 leading spaces and my code here
</code></pre>
<p>new parapraph</p>
```
