### ISSUE TITLE
nested html links are broken with parse_block_html 

### ISSUE THREAD

**Issue by jvanasco** [lepture/mistune#137]
this is a variant of #81

    example_in = '<div><a href="https://example.com">Example.com</a></div>'
    mistune.markdown(example_in, escape=False, parse_block_html=True)

will generate:

    <div><a href="<a href="https://example.com"&gt;Example.com">https://example.com"&gt;Example.com</a></a></div>

if escape is toggled to True, it is also broken:

   '&lt;div&gt;&lt;a href="&lt;a href="https://example.com"&gt;Example.com"&gt;https://example.com"&gt;Example.com&lt;/a&gt;&lt;/a&gt;&lt;/div&gt;

**Comment by lepture** [comment]
Current implementation of `parse_block_html=True` is not working well.

**Comment by frostming** [comment]
After a deep look into the source code, the root cause is when parsing the html body with `inline`, it uses a subset of default rules which doesn't contain `inline_html` rule. Then the body with urls will be captured by `url` rule.

I am glad to send a pull request

**Comment by lepture** [comment]
@frostming yes, please.
