### ISSUE TITLE
code block with empty line within list items not generate properly

### ISSUE THREAD

**Issue by crazytroll** [lepture/mistune#142]
Hi, when i generate list item with code block inside, if the code block has empty line the generated result seems not render properly. here is the example markdown.

https://gist.githubusercontent.com/crazytroll/2763efcfeb6c4e3afdbc72380d2afcc0/raw/b387984733bb7fe1c15c37ff663eefd6de93b7d4/markdown_with_empty_lines.md

here is the generated result, it seems some code block directive did not been parsed.

https://gist.githubusercontent.com/crazytroll/2763efcfeb6c4e3afdbc72380d2afcc0/raw/b387984733bb7fe1c15c37ff663eefd6de93b7d4/markdown_with_empty_lines.html

if i deleted these empty lines(inside the last two code block):

https://gist.github.com/crazytroll/2763efcfeb6c4e3afdbc72380d2afcc0/raw/b387984733bb7fe1c15c37ff663eefd6de93b7d4/markdown_without_empty_lines.md

then the it works well. here is the generated result: 

https://gist.github.com/crazytroll/2763efcfeb6c4e3afdbc72380d2afcc0/raw/b387984733bb7fe1c15c37ff663eefd6de93b7d4/markdown_without_empty_lines.html

Thanks.

**Comment by lepture** [comment]
@crazytroll please make your issue readable. Your example is a block quote.

**Comment by crazytroll** [comment]
@lepture sure, the block quote has been removed.

**Comment by lepture** [comment]
@crazytroll It is still not readable. I can't figure out your input text. If you find it really hard to write it in Markdown. Please create a gist for it.

**Comment by crazytroll** [comment]
Hi, @lepture  using the gist now, is it ok?

**Comment by lepture** [comment]
Record: https://gist.github.com/crazytroll/2763efcfeb6c4e3afdbc72380d2afcc0

**Comment by lepture** [comment]
please try v2.0.0a1
