### ISSUE TITLE
Ability to render custom tags

### ISSUE THREAD

**Issue by codevenkat** [lepture/mistune#145]
So basically, I am using mistune to store my blog posts. And sometimes I have some images or iframes or other tags that I only use in that article. So I want to be able to render customly, using some syntax like : `~img-href"link"alt"image"~` and it would be parsed as `<img href="link" alt="image"`. It is not just for that tag but any custom tag we want to make, like `~anytag~` render as `<anytag>`.

**Comment by lepture** [comment]
You can always use HTML in Markdown.
