### ISSUE TITLE
Parser confused by empty triple backtick code block

### ISSUE THREAD

**Issue by matthew-brett** [lepture/mistune#146]
Thanks for the nice library.   While I was doing some unit tests, I found this problem.

For the following code:

    import mistune

    in_str = """\
    Text

    ```
    ```

    More text

    ```
    # Comment
    ```
    """

    print(mistune.markdown(in_str))

I get:

```
<p>Text</p>
<pre><code>```

More text
</code></pre>
<h1>Comment</h1>
<p>```</p>
```

The output looks correct to me without the last backtick code block...

**Comment by lepture** [comment]
And what's the expected output?

**Comment by matthew-brett** [comment]
This is what pandoc gives for the same input:

```
<p>Text</p>
<pre><code></code></pre>
<p>More text</p>
<pre><code># Comment</code></pre>
```

That was also what I was expecting ...

**Comment by frostming** [comment]
minimal version:
````
```
```

```
```
````

**Comment by lepture** [comment]
please try v2.0.0a1

**Comment by matthew-brett** [comment]
Looks good - thanks.
