### ISSUE TITLE
BlockLexer.parse() is not idempotent

### ISSUE THREAD

**Issue by lastcoolnameleft** [lepture/mistune#147]
I would expect that calling parse two times with the same value would return the same result; however, it appears to append.  

```
>>> import mistune
>>> lexer = mistune.BlockLexer()
>>> lexer.parse('foo')
[{'type': 'paragraph', 'text': 'foo'}]
>>> lexer.parse('foo')
[{'type': 'paragraph', 'text': 'foo'}, {'type': 'paragraph', 'text': 'foo'}]
```

**Comment by lepture** [comment]
The `parse` method actually behaves like `feed`. To archive your goal:

```python
lexer = mistune.BlockLexer()

def block_parse(text)
    lexer.tokens = []
    return lexer.parse(text)
```

---

No, I can't change the `BlockLexer.parse`, it should behave like `feed`.

**Comment by lastcoolnameleft** [comment]
Thanks for the explanation and suggestion. That’s essentially what I implemented myself.

Are you open to a PR to add a block_parse() function so that an idempotent parser is available natively?

________________________________

**Comment by lepture** [comment]
@lastcoolnameleft Thanks, but no. There is a plan to rewrite mistune, but currently I don't have much time, since my focus is on https://github.com/lepture/authlib

This is not a bug, I don't think it is very important.
