### ISSUE TITLE
The following content is decoded incorrectly

### ISSUE THREAD

**Issue by ziming2018** [lepture/mistune#151]
**222222222222222222222** 

    _3333333333333333333_ 

    ----------

    # ddddddddddddddddddddddd

    * dddddddddddddddddd
    * hhhhhhhhhhhhhhhhh
    * uuuuuuuuuuuuuuuu

    1. ggggggggggggggg
    2. rrrrrrrrrrrrrrr
    3. yyyyyyyyyyyyyyyy

**Comment by lepture** [comment]
The minimal version is:

```
* unordered list

1. ordered list
```

**Comment by ziming2018** [comment]
v0.8.3

**Comment by frostming** [comment]
@lepture 
I found that in mistune, different bullets (*/+/-) are parsed as the same list, while GitHub recognizes them as separate lists, refer to https://github.com/lepture/mistune/blob/master/tests/fixtures/extra/same_bullet.html

So I wonder if you would like to change to the GitHub style.
And I can send a pull request about this issue.

**Comment by lepture** [comment]
Fixed by @frostming
