### ISSUE TITLE
What does parse_block_html and parse_inline_html mean?

### ISSUE THREAD

**Issue by dAnjou** [lepture/mistune#155]
I don't understand the description:

> **parse_block_html**: parse text only in block level html.
> **parse_inline_html**: parse text only in inline level html.

**Comment by lepture** [comment]
with `parse_block_html=True`

```html
<div>**text**</div>
```

will be:

```html
<div><strong>text</strong></div>
```

**Comment by dAnjou** [comment]
Sorry, I must be really slow, I still don't get it 😕

**Comment by lepture** [comment]
1. `parse_block_html=True`: parse text with markdown gram in block level HTML tags.
2. `parse_inline_html=True`: parse text with markdown gram in inline level HTML tags.
