### ISSUE TITLE
Markdown tables inside of ordered lists don't get parsed

### ISSUE THREAD

**Issue by supersam654** [lepture/mistune#158]
When I nest a table inside of an ordered list (so the list numbers continue), the table doesn't get parsed into HTML.

```python
import mistune

content = """
1. List item 1

    | Title |
    | Value |

2. List item 2
"""

markdown = mistune.Markdown()
print(markdown(content))
```
Prints

```html
<ol>
<li><p>List item 1</p>
<p>| Title |
 | Value |</p>
</li>
<li><p>List item 2</p>
</li>
</ol>
```

even though I was expecting an HTML table inside of the list.

**Comment by lepture** [comment]
@supersam654 That is designed on purpose, if you think you need this feature, you can subclass `BlockLexter`, and change here: https://github.com/lepture/mistune/blob/master/mistune.py#L184

**Comment by nottrobin** [comment]
@lepture could you please expand a little more on why it was designed this way?

**Comment by nottrobin** [comment]
@lepture I tried to subclass `BlockLexer` as suggested:

``` python
#! /usr/bin/env python3

from mistune import BlockLexer, Markdown

class WebteamBlockLexer(BlockLexer):
    list_rules = (
        'newline', 'block_code', 'fences', 'lheading', 'hrule',
        'block_quote', 'list_block', 'block_html', 'text',
        'table', 'nptable',
    )

parse_markdown = Markdown(
        parse_block_html=True, parse_inline_html=True,
        block=WebteamBlockLexer()
    )

md_text = """
| Title |
| ----- |
| Value |

1. List item 1

    | Title |
    | ----- |
    | Value |

2. List item 2
"""

print(parse_markdown(md_text))
```

But it didn't work, giving the following output:

``` html
<table>
<thead><tr>
<th>Title</th>
</tr>
</thead>
<tbody>
<tr>
<td>Value</td>
</tr>
</tbody>
</table>
<ol>
<li><p>List item 1</p>
<p>| Title |
 | ----- |
 | Value |</p>
</li>
<li><p>List item 2</p>
</li>
</ol>
```

@lepture would you be able to help me understand where I went wrong?

**Comment by nottrobin** [comment]
Okay, I worked it out - the order in that list matters. So `table` needs to precede `block_html`.

So, for posterity, here's a working example of how to support tables in lists:

``` python
from mistune import BlockLexer, Markdown

class MyBlockLexer(BlockLexer):
    list_rules = (
        'newline', 'block_code', 'fences', 'lheading', 'hrule',
        'block_quote', 'list_block', 'table', 'block_html', 'text',
    )

parse_markdown = Markdown(block=MyBlockLexer())

print(
    parse_markdown("""
1. List item 1

    | Title |
    | ----- |
    | Value |

2. List item 2
""")
)
```

Which outputs:

``` html
<ol>
<li><p>List item 1</p>
<table>
<thead><tr>
<th>Title</th>
</tr>
</thead>
<tbody>
<tr>
<td>Value</td>
</tr>
</tbody>
</table>
</li>
<li><p>List item 2</p>
</li>
</ol>
```

**Comment by phseiff** [comment]
Did you manage to get the same thing to work with `mistune==2.0.0rc1`?

I'm currently trying, but subclassing `mistune.block_parser.BlockParser` doesn't seem to work anymore (errors due to a variety of reasons), and changing the `Markdown` object's rules order after creating it doesn't do the trick  either.

UPDATE: It does work, and it is even easier than subclassing `BlockParser` (or `BlockLexer`, which I assume is how it was called in older versions).
All you need to do is

```python
markdown = mistune.create_markdown(...)
# or markdown = mistune.Markdown(...)

markdown.block.list_rules += ['table', 'nptable']
```

Tested with `2.0.0rc1`.
