### ISSUE TITLE
Ignore YAML Front Matter

### ISSUE THREAD

**Issue by ozzywalsh** [lepture/mistune#159]
Is there anyway to have mistune ignore YAML front matter.
eg:
```
---
title: My Post
publication-date: 2018-07-10
author: John Smith
---
## Part 1
My amazing post.
```

**Comment by ozzywalsh** [comment]
On second thoughts, I could filter it out before passing it to mistune. Would make a nice feature though.

**Comment by lepture** [comment]
Solve this by yourself. Mistune is a markdown parser.
