### ISSUE TITLE
spaces in html tags

### ISSUE THREAD

**Issue by bbadzioch** [lepture/mistune#161]
The following works as expected:

```
import mistune
markdown = mistune.Markdown()
markdown('<span style="color:red;">test</span>')
```
output:

`<p><span style="color:red;">test</span></p>\n`

However, adding a space either before or after `=` affects parsing. Input:

`markdown('<span style ="color:red;">test</span>')`

(note a space before `=`) produces the following output:

`<p>&lt;span style ="color:red;"&gt;test&lt;/span&gt;</p>\n`

This does not happen with  the `parse_block_html=True` option. Input

```
markdown = mistune.Markdown(parse_block_html=True)
markdown('<span style ="color:red;">test</span>') 
```
produces the following:

`<p><span style ="color:red;">test</span></p>\n`

**Comment by lepture** [comment]
Fixed in https://github.com/lepture/mistune/commit/4ad66e28ebdf509b25fbc6cc33d3997aa0dabffd
