### ISSUE TITLE
Multiple XSS

### ISSUE THREAD

**Issue by ngsimon** [lepture/mistune#172]
Hello, 

Following the hack.lu CTF 2017 challenge on mistune, multiple XSS were discovered.
The link of the CTF write-up can be found here: https://ctftime.org/task/4773

Best regards,

**Comment by ngsimon** [comment]
Additional links:
- https://www.pwndiary.com/write-ups/hack-lu-ctf-2017-mistune-write-up-web150/
- https://theromanxpl0it.github.io/ctf_hacklu17/mistune/
- https://rawsec.ml/en/Hacklu-2017-write-up/#150-mistune-web

**Comment by lepture** [comment]
Could you verify it with the latest version? They are all invalid.
