### ISSUE TITLE
Terminal Renderer

### ISSUE THREAD

**Issue by vext01** [lepture/mistune#173]
Hi,

I've been looking for a markdown renderer which can format for the terminal. I found a couple on PyPI, but they have all had one issue or another.

Would there be interest in implementing this for mistune? It looks like mistune has the flexibility to implement such a feature without too much fuss.

All I'm really envisaging is a simple renderer which:

 * Wraps paragraphs to the terminal width (Python std lib has the `textwrap` module).
 * Underlines headings.
 * Preserves wrapping between triple quotes.
 * Inserts appropriate spacing between elements.

Thanks

**Comment by lepture** [comment]
You can create it by your own. There is not built-in terminal renderer.
