### ISSUE TITLE
Is this possible to use several custom lexers?

### ISSUE THREAD

**Issue by paternal** [lepture/mistune#174]
The [`Markdown`](http://mistune.readthedocs.io/en/latest/#mistune.Markdown) class takes as parameter `inline`: *An inline lexer class or instance* (same for `block`).

All the examples I saw about adding new lexers use only *one* custom lexer.

Let's imagine that I want to parse markdown text with both [math](https://github.com/lepture/mistune-contrib/blob/0a2409776bfa3d444d9e480136aff02057b1d8b7/mistune_contrib/math.py) and [wikilink](https://github.com/lepture/mistune#lexers) lexers enabled. How can I do that?

Thanks,
-- Louis

**Comment by lepture** [comment]
You need to combine them together to create a new lexer. It is the only way for now.

**Comment by thisispiggy** [comment]
Could you explain how to combine into a new lexer? I can only write one return function. I couldn't figure out how to return for 2 separate grammars.

**Comment by lepture** [comment]
This is a little hard for mistune 0.x. But it is easy in v2. See https://github.com/lepture/mistune/tree/v2.0/mistune/plugins there are many plugins in v2

**Comment by lepture** [comment]
please try v2.0.0a1
