### ISSUE TITLE
Cannot use the ORIGINAL markdown parser after using a custom InlineLexer

### ISSUE THREAD

**Issue by jeicoo** [lepture/mistune#177]
Upon extending the default `InlineLexer`, I  can't parse a `markdown` using the default parser.

```python
class CustomRenderer(Renderer):
    # custom tags

class CustomLexer(InlineLexer):
    def enable(self):
        self.rules.custom_tag = re.compile(r'your custom pattern')
        self.default_rules.insert(3, 'custom_tag')

custom_renderer = CustomRenderer()
custom_lexer = CustomLexer(custom_renderer)
custom_lexer.enable()
custom_markdown = Markdown(renderer=custom_renderer, inline=custom_lexer)
default_markdown = Markdown()
```
Using the `custom_markdown` should not be a problem. However, using the `default_markdown` is another story. You will get this error:
```python
html = default_markdown('#markdown')
  File "/your/path/to/mistune/mistune.py", line 550, in manipulate
    pattern = getattr(self.rules, key)
AttributeError: 'InlineGrammar' object has no attribute 'custom_tag'
```

I found out that after inserting into the `default_rules` will update the `default_rules` of the `default_markdown` as well. 

This is due to the fact that `default_rules` in `InlineLexer` class is a `class attribute`.
That means any changes in the class's `default_rules` will reflect in other instances of the said class.

https://github.com/lepture/mistune/blob/master/mistune.py#L508

Looking forward for this issue to be fixed.

**Comment by pronobis** [comment]
+1

**Comment by lepture** [comment]
please try v2.0.0a1
