### ISSUE TITLE
Simple to crash mistune with a RecursionError

### ISSUE THREAD

**Issue by rspeer** [lepture/mistune#178]
Input: N copies of the character `>`, with N >= 1000

Expected output (what pandoc gives): N nested `<blockquote>` tags, with nothing in the innermost tag

Acceptable output: maybe the blockquotes just stop after a while and contain literal `>`s or something

Actual behavior: Mistune crashes with a RecursionError

Markdown input is not necessarily trustworthy -- it's not up to the programmer whether a user will post 1000 greater-than signs. I don't think catching RecursionError is part of the API of Mistune, so I think it's up to Mistune to recover in this case, perhaps by limiting the depth of its parsing before it hits Python's limit.

**Comment by lepture** [comment]
fixed in 0.8.4
