### ISSUE TITLE
Runtime Error for sublists 

### ISSUE THREAD

**Issue by tbille** [lepture/mistune#181]
Hi there, I have a little bug with the list parser. When having a list with sub items:
```md
+ list
+ with
  + sub
  + items
```
I get this error: 
```
builtins.RuntimeError

RuntimeError: Infinite loop at: 
+ sub
+ items
```

I should be able to convert this into a list with subitems :smile:

**Comment by lepture** [comment]
Can you verify it with the master code? I can't reproduce it.

**Comment by tbille** [comment]
@lepture 
I extending the `BlockLexer` class and I forgot to add the rule `newline`... This was causing the bug. I am closing this issue since it comes from me :smile:
