### ISSUE TITLE
Rendering sub-lists for white-space sensitive output formats.

### ISSUE THREAD

**Issue by vext01** [lepture/mistune#182]
The input:

```
 + list
 + with
     + sub
     + items
```

Should format as:

 + list
 + with
     + sub
     + items

Mistune's default renderer does the right thing by nesting `ul` tags:
```
<ul>
<li>list</li>
<li>with<ul>
<li>sub</li>
<li>items</li>
</ul>
</li>
</ul>
```

But how would you make a text renderer do the right thing using the API? Unless I'm mistaken, there's no way to know what indent level any given list item should be at.

How would you make output like:
```
 * list
 * with
     * sub
     * items
```

Cheers

**Comment by vext01** [comment]
Shouldn't `def list_item(self, text):` also pass a `level` parameter? Then you could do:

```
def list_item(self, text, level):
    return "%s* %s" % ("  " * level, text)
```

**Comment by lepture** [comment]
It seems a reasonable request. I'm working on a new implementation of mistune in `wip-scanner` branch, it can be added into that.

**Comment by weaming** [comment]
Sublist not render properly yet. https://md.drink.cafe/md/src-readme/html

**Comment by lepture** [comment]
please try v2.0.0a1
