### ISSUE TITLE
Recommended way to allow a CSS class notation? 

### ISSUE THREAD

**Issue by ragona** [lepture/mistune#183]
Any thoughts on a good way to allow a custom CSS class notation? [This is the basic idea](https://digitaldrummerj.me/styling-jekyll-markdown/) of what I'm thinking about, and I'd love to hear what you think a good path is with Mistune.

**Comment by lepture** [comment]
It seems not a good design. Markdown is designed to be easy-to-read and easy-to-write. The CSS class notation looks weird and not that easy to read or write.

But it is possible to create such a plugin for Mistune. The redesigned mistune in `wip-scanner` branch provided an easy way to create plugins. Stay tuned for the new mistune.

**Comment by ragona** [comment]
Yeah, I don't love that implementation either, but I do see where the feature would be helpful. Right now I find myself overriding things like `#####` -- "okay, that's the 'date' sub-header" for a blog, as an example. Thanks for the comment though, and let me know when you think it's ready for a pass at a plugin.
