### ISSUE TITLE
Combining Renderers individually defined.

### ISSUE THREAD

**Issue by karlcow** [lepture/mistune#190]
With individually defined renderers, I can call them independently and this is working:

```python
from markup_extension import Blockquote
from markup_extension import Photo

import mistune

renderer = Photo()
markdown = mistune.Markdown(renderer=renderer)

renderer = Blockquote()
markdown = mistune.Markdown(renderer=renderer)
```

but what if I want the two renderers being mixed? in python markdown, it is possible to do something along:

```python
markdown.markdown(text, extensions=['photo', 'blockquote', 'meta'])
```

**Comment by lepture** [comment]
See my work in wip-scanner branch.

**Comment by karlcow** [comment]
Checking https://github.com/lepture/mistune/tree/wip-scanner thanks.

**Comment by karlcow** [comment]
That would indeed answer my needs I guess for https://github.com/karlcow/koke
Thanks.

**Comment by lepture** [comment]
please try v2.0.0a1 now
