### ISSUE TITLE
Closing tags of nested html is escaped

### ISSUE THREAD

**Issue by aioobe** [lepture/mistune#195]
This:

    mistune.markdown("a <div><div>b</div></div> c", escape=False)

produces this:

    <p>a <div><div>b</div>&lt;/div&gt; c</p>
                          ^^^^^^^^^^^^

I note however that this works as expected:

    mistune.markdown("a <div><b>b</b></div> c", escape=False)

Produces:

    <p>a <div><b>b</b></div> c</p>

Perhaps mistune things the outer `<div>` is closed by the inner `</div>` and hops back to text mode?

**Comment by lepture** [comment]
please try v2.0.0a1
