### ISSUE TITLE
autolinks at the beginning of a line

### ISSUE THREAD

**Issue by idnsunset** [lepture/mistune#200]
For a paragraph like:

```
this is a long sentence..., send a email to
<mymailbox@gamil.com> ...
```

I expect the first line and the mail address to be wrapped within the same paragraph block and I think it should be rendered like this as autolink is an inline element, but mistune actually produces a separate paragraph for the mail address. Although I could simply append the mail address to the previous line without a line break to work around this issue, as for the text width limitation set in my text editor, I still expect the markdown text to be processed more correctly.

The block grammar about paragraph in mistune maybe the cause.

```python
    paragraph = re.compile(
        r'^((?:[^\n]+\n?(?!'
        r'%s|%s|%s|%s|%s|%s|%s|%s|%s'
        r'))+)\n*' % (
            _pure_pattern(fences).replace(r'\1', r'\2'),
            _pure_pattern(list_block).replace(r'\1', r'\3'),
            _pure_pattern(hrule),
            _pure_pattern(heading),
            _pure_pattern(lheading),
            _pure_pattern(block_quote),
            _pure_pattern(def_links),
            _pure_pattern(def_footnotes),
            '<' + _block_tag,
        )
    )
```

`<mymailbox@gmail.com` matches against `'<' + _block_tag`, thus it is not counted along with the previous lines into the same paragraph.

**Comment by lepture** [comment]
I've tested it with v0.8.4 code. They are in the same paragraph.
