### ISSUE TITLE
list_rules and footnote_rules in BlockLexer

### ISSUE THREAD

**Issue by idnsunset** [lepture/mistune#201]
It's just a suggestion about using `list` instead of `tuple` for `BlockLexer.list_rules` and `BlockLexer.footnote_rules`, so that we can handle our own block markups nesting in list and footnote. For instance, an admonition block rule implemented by myself may need to be added not only to `default_rules` but also `list_rules` and `footnote_rules`.
I know I could implement a subclass or simply just convert tuple to list,  but having these two block rules as list type out of box seems more reasonable.

**Comment by lepture** [comment]
please try v2.0.0a1
