### ISSUE TITLE
block_code should be triggered even without language

### ISSUE THREAD

**Issue by zokrezyl** [lepture/mistune#202]
This: ```print("this is source code")```

should be rendered like here on github...

This ```python
print("this is something else")```

What about this:

```for i in range(10):```

When language is not specified the codespan is triggered.

**Comment by lepture** [comment]
I don't understand your question.

**Comment by zokrezyl** [comment]
In your parser a "block code" is not interpreted as a block code if it does not contain the language token. Other parsers (github) consider a block code a "block code" without language token.

**Comment by zokrezyl** [comment]
@lepture ... for me this is a bug.. Please reopen the issue

**Comment by lepture** [comment]
![image](https://user-images.githubusercontent.com/290496/63573293-e3a24a00-c5bf-11e9-936a-078b681cdab6.png)

I still don't understand your problem. Here is my test code.

**Comment by zokrezyl** [comment]
Hi, am sorry, cannot reproduce the problem. Not sure if I had an older version. Will come back once I find again the problem
