### ISSUE TITLE
Identifying List Level

### ISSUE THREAD

**Issue by joswr1ght** [lepture/mistune#204]
I am not sure how to use Mistune to format list elements to render Markdown. Is there a way to identify the level for indentation of the list element?

The `MdRenderer` contribution attempts to decode list elements by flagging the `list_item` values and parsing them with `list`, but this does not preserve indentation levels for sub-list items:

```
$ cat Foo.md
+ Head List 1
    + List item 1
    + List item 2

$ ./listhandler.py
* Head List 1* List item 1
* List item 2
```

Is there a way to identify the indentation level for the list item, or a Mistune example where sub-list elements are processed? Thanks!
[listhandler.txt](https://github.com/lepture/mistune/files/3549029/listhandler.txt)

**Comment by lepture** [comment]
It is already available in mistune v2.0, see https://github.com/lepture/mistune/blob/v2.0/mistune/renderers.py#L188

**Comment by lepture** [comment]
It is available in master code now.

**Comment by alexanderkjeldaas** [comment]
and gone in mistune 3?

**Comment by lepture** [comment]
@alexanderkjeldaas check the markdown renderer, it is in the token.
