### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by perrette** [lepture/mistune#207]
The only example command of the readme fails...

```
import mistune       
mistune.__version__ 
'0.8.4'
mistune.html('test.md')
AttributeError: module 'mistune' has no attribute 'html'
```

**Comment by lepture** [comment]
> NOTE: This is the re-designed v2 of mistune. Check v1 branch for earlier code.

**Comment by lepture** [comment]
v2 is not released yet. But, what you are looking for is `v1` branch code.

**Comment by perrette** [comment]
I'm just saying, that could be made clearer in the README. Just as a feedback from a first-time user.

**Comment by perrette** [comment]
I understand, going specifically to v0.8.4 readme got me the right readme. Confusing was that the pip version is very recent yet the master's readme already further. But fine, my mistake. Thanks for the work.
