### ISSUE TITLE
Use more efficient string concatenation method

### ISSUE THREAD

**Issue by sicklybeans** [lepture/mistune#209]
Not sure if you accept issues from random users, but I thought this was worth mentioning.

I'm using mistune 0.8.4 and I looked through the implementation and noticed that by modifying how the output is constructed, there might be a potentially massive speedup, especially for large input files.

The main problem is the string concatenation method. It seems like the general loop of this parser is to do something like:

    output = ''
    while something:
        output += parse_next()

This means that for each block parsed, the entire output has to be recopied since python strings are  immutable. [This page](https://waymoot.org/home/python_string/) has some nice suggestions for speedups (the existing implementation roughly corresponds to their method 1)

There is a similar problem in the preprocessing loop which calls `replaceall` on the entire input. Though this might not be as trivial to fix

**Comment by EmilStenstrom** [comment]
@sicklybeans Could you give a reference to where in the code this happens? Is it spread out over multiple places or concentrated to one part of the code?

**Comment by sicklybeans** [comment]
@EmilStenstrom Sorry I was using version 0.8.4 which did rely on an inefficient concatenation method (`+=`) but if I understand the code correctly, it looks like [version 2.0 does a much better job](https://github.com/lepture/mistune/blob/dcaf974a6bf8e70bdee57d7333b6eac0a2ff14c5/mistune/block_parser.py#L246)
