### ISSUE TITLE
Support for Front Matter?

### ISSUE THREAD

**Issue by EmilStenstrom** [lepture/mistune#211]
I have a blog with markdown files generated by Jekyll. They use Markdown files that has a metadata block on top that contains yaml. Is this something that mistune would be willing to support? Jekyll is a very common blog engine, so I think it would be useful to many!

```markdown
---
id: 29
title: How this website was built
date: 2005-12-20T00:00:36
categories:
  - CSS
---
Hi there early readers!
```

**Comment by karlcow** [comment]
@EmilStenstrom 

The issue here is that there are two common formats:
* yaml
* mmd (multi-markdown)

```
---
id: 29
title: How this website was built
date: 2005-12-20T00:00:36
categories:
  - CSS
---
Hi there early readers!
```

and

```
id: 29
title: How this website was built
date: 2005-12-20T00:00:36
categories: CSS

Hi there early readers!
```

for the `mmd` part I usually pre-parse:


```python
import re

META = re.compile(r'^(\w+):\s*(.+?)\n')


def preparse(text):
    """Parse the given text into metadata and strip it for a Markdown parser.
    :param text: text to be parsed
    """
    metadata = {}
    m = META.match(text)

    while m:
        key = m.group(1)
        value = m.group(2)
        value = INDENTATION.sub('\n', value.strip())
        metadata[key] = value
        text = text[len(m.group(0)):]
        m = META.match(text)
    return metadata, text
```

**Comment by EmilStenstrom** [comment]
@karlcow I'm not sure if you are expressing any opinion on my issue, or just adding more information/suggestions around how this could be solved. Anyways: Seems like "---" could be used to differentiate between the two formats.

**Comment by karlcow** [comment]
Just explaining how I do currently for a similar issue (mmd).
Not sure if it should be added to mistune or [just create a plugin](https://mistune.readthedocs.io/en/latest/plugins.html) around it. :)

**Comment by lepture** [comment]
Yes, that can be done with plugins. Just register a `before_parse_hooks` to parse the front matter into `state`:

```python
def parse_front_matters(md, s, state):
    # fake method, you need to write it your own
    front_text, markdown_text = split_front_matter(s)
    state['front_matters'] = yaml.load(front_text)
    return markdown_text, state

def plugin_front_matters(md):
    md.before_parse_hooks.append(parse_front_matters)
```

It could be something like this.

**Comment by EmilStenstrom** [comment]
@lepture Thanks, I'll try that.

Are you also saying that you don't want this as an "official" plugin, that is included in mistune?

**Comment by lepture** [comment]
I thought it may require an external dependency of `yaml`. I'd like to keep mistune dependency free.

**Comment by EmilStenstrom** [comment]
Supporting front matter requires yaml, so I don't think this can be dependency free. Closing.

**Comment by quantology** [comment]
For posterity, @karlcow 's snippet above is missing a line; the full version is here: https://github.com/lepture/mistune-contrib/blob/master/mistune_contrib/meta.py

@EmilStenstrom let me know if you ended up with a gist of the above, I'm playing around with something similar

**Comment by EmilStenstrom** [comment]
@quantology I ended up parsing the frontmatter separately before the markdown. Like this: https://github.com/EmilStenstrom/friendlybit/blob/master/friendlybit/views.py#L79

**Comment by x2f** [comment]
In case it helps other people interested in YAML frontmatter processing: consider using https://github.com/eyeseast/python-frontmatter. Here is a simple example:

```
with open("text.md", "r") as f:
    obj = frontmatter.load(f)
    html = mistune.html(obj.content)
    with open("text.html", "w") as of:
        of.write(html)
```
