### ISSUE TITLE
Any ideas about saving and exposing state in class Markdown?

### ISSUE THREAD

**Issue by schwarzichet** [lepture/mistune#219]
I am writing a Yaml front matter plugin for mistune. I have noticed that in #211 you suggest a way to deal with front matter. The front matter is stored in `state` , but `state` will get lost in parsing.
I wonder if in the future it is possible to save `state` in `class Markdown` for future use, or you just don't want to make this change, then a plugin may be not proper for this case.

**Comment by lepture** [comment]
You can pass a `state` dict yourself:

```py
state = {}
md = Markdown()
md.parse(text, state)
```

In this way, you can access `state` after parsing.

**Comment by schwarzichet** [comment]
I have never thought of this way,  thank you
