### ISSUE TITLE
Nested tags not being rendered correctly.  

### ISSUE THREAD

**Issue by Natay** [lepture/mistune#223]
Hello , 

I noticed nested bold tags,  < b > , are not rendered correctly.

Here is a test case with the issue:

    import mistune
    test = "<b><b>foo</b></b>"
    html = mistune.markdown(escape=False, text=test) 
    print(html)
    >>>'<p><b><b>foo</b>&lt;/b&gt;</p>\n'

It seems like other tags are still rendered correctly. 

    import mistune
    test = "<div><div>foo</div></div>"
    html = mistune.markdown(escape=False, text=test) 
    print(html)
    >>>'<div><div>foo</div></div>'

Is this expected behavior with some tags?

**Comment by ialbert** [comment]
The problem also manifests itself with `<i>` and `<a>` tags but not with `<p>` or `<div>`.

When the misrender occurs it also adds an extra newline character at the end.

**Comment by lepture** [comment]
which version are you using? please try with master code at first.

**Comment by yujiri8** [comment]
Works correctly for me with mistune 2.0.0a2.

**Comment by ialbert** [comment]
we used what gets installed from pypi.

We have quite a big battery of custom rules that we deploy, will those also work with the new version?

By the way we had to monkey path mistune to isolate the rules at class instance level

https://github.com/ialbert/biostar-central/blob/master/biostar/forum/markdown.py#L119

**Comment by lepture** [comment]
Please consider using mistune v2 which has a better architecture.

**Comment by lepture** [comment]
@ialbert you can find how to write plugins in v2: https://mistune.readthedocs.io/en/latest/advanced.html#create-plugins

**Comment by ialbert** [comment]
@lepture ok, thanks for the note, we'll give it a go
