### ISSUE TITLE
Pip upload out of date?

### ISSUE THREAD

**Issue by yujiri8** [lepture/mistune#225]
I installed mistune from pip and got 0.8.4. Sounds like that's pretty far out of date...?

**Comment by lepture** [comment]
You need to specify version to install mistune 2.0:

```
pip install mistune==2.0.0a2
```

**Comment by yujiri8** [comment]
Oh nice. Looks like this library will outmode the hacks and manual modifications I had to made to the other markdown library I was using ([python-markdown2](/trentm/python-markdown2)).

I also noticed the `parse_inline_html` and `parse_block_html` params seem to've been made default. I guess that's nice tho
