### ISSUE TITLE
Spoilers

### ISSUE THREAD

**Issue by yujiri8** [lepture/mistune#226]
Some markdown implementations allow `>!` for a block spoiler, and `>! ... !<` for an inline spoiler. Will this be implemented?

**Comment by lepture** [comment]
Is there a spec for this? I want to know who defined this gram?

**Comment by yujiri8** [comment]
Mm, it doesn't look like there is a spec, a few implementations have it but each do it differently.

[python-markdown2](/trentm/python-markdown2) puts `class="spoiler"` on a line starting with `>!` (it also still becomes a blockquote, so apparently it only works with blockquotes). [Stackexchange](https://meta.stackexchange.com/questions/72877/whats-the-exact-syntax-for-spoiler-markup) seems the same way. Discord uses `||...||`. Reddit spoilers text between `>!...!<` (which is useful so it can be inline). I think Reddit's syntax is the best, especially since the start and end tag are distinguishable.

**Comment by lepture** [comment]
Implemented in v3.
