### ISSUE TITLE
Nested fenced code blocks have an extra space

### ISSUE THREAD

**Issue by yujiri8** [lepture/mistune#228]
Input:
```
* test
    ```
    print()
    ```
```
Output:
```
<ul>
<li>test<pre><code>  print()
</code></pre>
</li>
</ul>
```

Note the extra two spaces inserted. It seems to work with an indented code block, but then I have to put no blank line between it and then next content after the list element (or else it shows up with a trailing blank line inside the code), which looks very ugly.

**Comment by lepture** [comment]
Fixed in master code
