### ISSUE TITLE
Multiple pairs of __ interfere with each other

### ISSUE THREAD

**Issue by yujiri8** [lepture/mistune#229]
Input: `__one__ and __two__`

Output: `<strong>one__ and __two</strong>`

With asterisks (or one of each) it works:

Input: `**one** and **two**`

Output: `<strong>one</strong> and <strong>two</strong>`

**Comment by lepture** [comment]
please test it with master code. it was fixed by https://github.com/lepture/mistune/commit/f9be399b4871ee7f15f55fcba280a58bd65d13b2
