### ISSUE TITLE
Trailing whitespaces not stripped

### ISSUE THREAD

**Issue by satyamtg** [lepture/mistune#231]
If we run mistune with HTMLRenderer, and if the input contains trailing whitespace in some lines, then they should automatically be stripped and handled. Currently mistune crashes with list index out of bounds error.

**Comment by lepture** [comment]
It was fixed by https://github.com/lepture/mistune/commit/f9be399b4871ee7f15f55fcba280a58bd65d13b2

I'll make a new release soon.

**Comment by lepture** [comment]
v2.0.0a3 was released
