### ISSUE TITLE
Trying to implement a plugin for checkboxes

### ISSUE THREAD

**Issue by dsancheznet** [lepture/mistune#233]
Hello everyone,
I'm working on a plugin to render checkboxes as in https://help.github.com/es/github/managing-your-work-on-github/about-task-lists which are immensely useful and although not being part of the original MD specification, they are part of the Github MD. 

My code is as following (based on the example you have given a few hours back):
```python3
import re

__all__ = ['plugin_checkbox']

CHECKBOX_PATTERN = (
    r'^-[ ]\[([ xX])\][ ]?([^\n]*)'
)

def parse_checkbox(self, m, state):
    check = m.group(1)
    text = m.group(2)
    if check.upper()=='X':
        return 'checkbox', text, True
    else:
        return 'checkbox', text, False

# define how to render HTML
def render_html_checkbox(text, state):
    if state==False:
        status=""
    else:
        status=" checked"
    return f'<input type="checkbox"{status}>{text}'

def plugin_checkbox(md):
    md.inline.register_rule('checkbox', CHECKBOX_PATTERN, parse_checkbox)
    md.inline.rules.append('checkbox')
    if md.renderer.NAME == 'html':
        md.renderer.register('checkbox', render_html_checkbox)
```

But whenever I try to hook up my plugin I get the following error:
`NameError: name 'plugin_checkbox' is not defined`

What am I doing wrong?

Regards

**Comment by lepture** [comment]
Mistune has built-in task lists plugin now. Check out https://github.com/lepture/mistune/blob/master/mistune/plugins/task_lists.py

It will be released in next release.

**Comment by lepture** [comment]
Here is the documentation: https://mistune.readthedocs.io/en/latest/plugins.html#task-lists
