### ISSUE TITLE
[REQUEST] Please add support for abbreviatons

### ISSUE THREAD

**Issue by dsancheznet** [lepture/mistune#234]
Please add support for abbreviations as explained in the [Markdown Extra](https://michelf.ca/projects/php-markdown/extra/#abbr) proposal. 

```
*[ACRONYM]: Tooltip text
```

Pandoc and similar renderers do include the tag, while Github does not.

I think it would be a valuable addition...

Regards
Merlin

**Comment by lepture** [comment]
Close it. We have abbr plugin now.
