### ISSUE TITLE
Picture url escape bug

### ISSUE THREAD

**Issue by ygcaicn** [lepture/mistune#238]
`mistune.html("![]('/media/name 1.png')")`
url contain backspace.

got:
```
'<p>![](/media/name 1.png)</p>\n'
```

expect:
```
'<p><img src="/media/name%201.png" alt="" /></p>\n'
```

**Comment by lepture** [comment]
Please paste your content in to this comment box here and click preview:

`![]('/media/name 1.png')`

The syntax you provided is wrong. The correct syntax has no quote for image url.

**Comment by ygcaicn** [comment]
> Please paste your content in to this comment box here and click preview:
> 
> `![]('/media/name 1.png')`
> 
> The syntax you provided is wrong. The correct syntax has no quote for image url.

Sorry, this is my mistake in writing the issue, the problem exists.

Thanks.

**Comment by lepture** [comment]
Please paste your content here to test:

```
![](/media/name 1.png)
```

Click preview. Your syntax is wrong, there shouldn't be any blank space in the url. Use `%20` to replace space:

```
![](/media/name%201.png)
```
