### ISSUE TITLE
Minor Documentation Typo

### ISSUE THREAD

**Issue by Amar1729** [lepture/mistune#240]
https://github.com/lepture/mistune/blame/14ce757ba0ff1f0d78c9f71f193ec4e3072c4836/docs/advanced.rst#L22

https://mistune.readthedocs.io/en/latest/advanced.html#use-renderers

```
class MyRenderer(mistune.HTMLRenderer):
    def codespan(self, text):
        if text.startswith('$') and text.endswith('$'):
            return '<span class="math">' + escape(text) + '</span>'
        return '<code>' + escape(text) + '</code>'

# use customized renderer
markdown = mistune.create_markdown(renderer=MyRenderer())
print(markdown('hi `$a^2=4`'))
```

Currently your example `MyRenderer` is showing how to render math, but I think you meant to render the text:

    'hi `$a^2=4$`'

(currently missing trailing `$`)

**Comment by lepture** [comment]
Thanks for your reporting. Fixed.
