### ISSUE TITLE
Line under quote is not considered part of quote

### ISSUE THREAD

**Issue by makeworld-the-better-one** [lepture/mistune#244]
Apologies if this just an issue on my side. But I found that the follow two lines would not be joined into the same quote, when passed to my custom renderer:
```
> first quote line
second line underneath
```

I assumed they would both be passed together to the `block_quote` function.

**Comment by karlcow** [comment]
```python
Python 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mistune
>>> text = """
... > one line
... another line
... 
... then some text
... """
>>> mistune.html(text)
'<blockquote>\n<p>one line</p>\n</blockquote>\n<p>another line</p>\n<p>then some text</p>\n'
```

**Comment by makeworld-the-better-one** [comment]
@karlcow Your example seems to agree with me, with the second line not part of the blockquote.
```html
<blockquote>
<p>one line</p>
</blockquote>
<p>another line</p>
```

**Comment by karlcow** [comment]
Yes I was just giving the example so the bug report would be more complete.

**Comment by makeworld-the-better-one** [comment]
Yes, I realize that now. Thanks! 

@lepture do you think a fix for this is possible?

**Comment by lepture** [comment]
Yes, it is possible. But I'm re-thinking of the syntax of Markdown. I like explicit, instead of the syntax you give, I would think:

```
> first line
> second line
```

is better. If the second line can be without `>`, what if

```
> first line
- second line (or list)
```

**Comment by makeworld-the-better-one** [comment]
Well it's more about what the spec says rather than what you think might be better.

> first line
- second line (or list)

Github seems to indicate that the second line would be a list. But you'd have to look at the spec to make sure.

**Comment by makeworld-the-better-one** [comment]
@lepture Could this be fixed?

**Comment by lepture** [comment]
@makeworld-the-better-one yes, it can be fixed. I don't have too much spare time in this library right now. But I'm happy to accept a PR.

**Comment by karlcow** [comment]
The [original spec](https://daringfireball.net/projects/markdown/syntax#blockquote) doesn't say too much about the rules in this circumstance: `>text1\n* text2` but it's "clear" for `>text1\ntext2` and `>text1\n\n* text2`.

So maybe the first issue to solve is `>text1\ntext2`. 

One problem at a time.

**Comment by karlcow** [comment]
We can check what [Dingus](https://daringfireball.net/projects/markdown/dingus) is doing.
And the result is "surprising" :) 

<img width="155" alt="Capture d’écran 2020-07-23 à 21 01 38" src="https://user-images.githubusercontent.com/505230/88284096-c32ac480-cd27-11ea-853c-d795e18590a4.png">


Another funny thing.

<img width="161" alt="Capture d’écran 2020-07-23 à 21 03 04" src="https://user-images.githubusercontent.com/505230/88284181-ee151880-cd27-11ea-9670-e95ee3e0e69f.png">

**Comment by karlcow** [comment]
And this is the [version from CommonMark](https://spec.commonmark.org/dingus/?text=%3E%20line%201%0A%3E%20line%202%0A%0A%0A%3E%20line%201%0Aline%202%0A%0A%0A%3E%20line%201%0A*%20item%201%0A) (this link doesn't work in Firefox I filed https://webcompat.com/issues/55791 )

<img width="1365" alt="Capture d’écran 2020-07-23 à 21 13 41" src="https://user-images.githubusercontent.com/505230/88285374-ebb3be00-cd29-11ea-8f2f-4ac66bcafa89.png">

**Comment by yujiri8** [comment]
Personally I think the behavior here makes perfect sense. I always use empty `>`'s when I want breaks in a blockquote:
```
> text
>
> next paragraph, same quote

# or

> text
> * item 1
> * item 2
```
I'm really surprised by the Dingus behavior. How would I put multiple separate blockquotes in a row? Would I need to do something hacky like put a non-breaking space inbetween them? I'd much rather keep mistune's current behavior.

**Comment by makeworld-the-better-one** [comment]
And to confuse things further, Github does this:
```
> test
test 2
```
Rendered:
> test
test 2

It keeps things on separate lines. This is what I expected CommonMark to do as well, weird.

**Comment by makeworld-the-better-one** [comment]
What has mistune done in the past when faced with different markdown implementations/specs ?

**Comment by karlcow** [comment]
I'm not the maintainer but… https://mistune.readthedocs.io/en/latest/intro.html#sane-commonmark

**Comment by karlcow** [comment]
Trying to find the right regex that would match the old and the new patterns.
https://regex101.com/r/wNYWvh/1/

Not there yet.

**Comment by makeworld-the-better-one** [comment]
Looks good, the thing missing seems to be detection of secondary lines that are not regular text lines, like bullet lines for example.

**Comment by karlcow** [comment]
Yes not sure it's entirely doable with only regex. look-ahead look-behind can't work with variables size pattern of spaces. 
I'll check later if I have time. My plate is a bit full today.

**Comment by makeworld-the-better-one** [comment]
@karlcow @lepture what's the status of this? Thanks.

**Comment by lepture** [comment]
I'm working on a new way to write the parser, which will make it easier to solve problem like this. Pure regex is just very hard to fix this problem.

**Comment by lepture** [comment]
This is fixed in v3.
