### ISSUE TITLE
Parsing Markdown blocks inside HTML blocks, and inline Markdown inside nested HTML elements

### ISSUE THREAD

**Issue by nottrobin** [lepture/mistune#247]
I'm trying to parse HTML similar to the following (in Mistune 0.8.4):

``` html
<details>
<summary>`some code`</summary>

**Something**

---

Some paragraph
</details>
```

But I can't find a way to make it create paragraphs or the HR, or parse the `<code>` block inside the `<summary>` tag:

``` python3
In [1]: from mistune import Markdown

In [2]: Markdown(parse_block_html=True, parse_inline_html=True)("<details>\n<summary>`some code`</summary>\n\n**Something**\n\n---\n\nSome paragraph\n</details>")
Out[2]: '<details>\n<summary>`some code`</summary>\n\n<strong>Something</strong>\n\n---\n\nSome paragraph</details>'
```

Is there any way to get Mistune to parse block markdown inside block HTML elements? Or to get it to parse `<code>` blocks inside inline HTML elements that are nested inside block HTML elements?

**Comment by lepture** [comment]
Mistune is following the rules defined by commonmark for HTML tags. In the commonmark processing way, it is impossible to get this goal done.

**Comment by lepture** [comment]
@nottrobin sure, it can be done with plugin.
