### ISSUE TITLE
Support for Python 2.6

### ISSUE THREAD

**Issue by xanok** [lepture/mistune#250]
I know Python 2.6 is old, but in the project that I working on we still use Python 2.6
I was able to port it to Python 2.6, it was not that difficult, most of the changes are related to init "set" datatypes. Would it be useful if I make a pull-request for it?

**Comment by yujiri8** [comment]
Python 2 hit EOL half a year ago. https://www.python.org/doc/sunset-python-2/

I'm not the maintainer here, but I strongly recommend you move your project to Python 3.

**Comment by lepture** [comment]
Actually, we are going to remove python 2 support in the next year.
