### ISSUE TITLE
HTMLRenderer's heading cannot be customised when DirectiveToc is used

### ISSUE THREAD

**Issue by Rhahi** [lepture/mistune#251]
using version 2.0.0a4,
HTMLRenderer's heading cannot be customised when DirectiveToc is used
for example, running the code below will result in two different behaviours.

```python
import mistune
import mistune.directives import DirectiveToc

class Renderer(mistune.HTMLRenderer):
    def heading(self, text, level):
        return 'changed_heading'

test_a = mistune.create_markdown(
        renderer=Renderer(),
        plugins=[])
test_b = mistune.create_markdown(
        renderer=Renderer(),
        plugins=[DirectiveToc()])

print(test_a("# text")) #returns 'changed_heading'
print(test_b("# text")) #returns '<h1 id="toc_1">text</h1>'
```

This is because when DirectiveToc is used, the rendering process uses render_html_threading (from mistune.directives.toc.py) instead.
This is not necessarily an issue, since it's impossible to handle arbitrary changes in the renderer while trying to put header ids in the html. Maybe this behaviour should be documented so that people can find which method to override when using DirectiveToc.

**Comment by lepture** [comment]
Try to customize with:

```py
def theading(self, text, level, tid):
    return 'changed toc heading'
```

**Comment by mauro-balades** [comment]
@lepture add this to the documentation because I was about to change to another markdown engine before seeing this issue.

**Comment by lepture** [comment]
@mauro-balades thanks, I've added it to documentation.

**Comment by EmpireJones** [comment]
I think the documentation might be slightly incorrect, as the function needs to be called `theading` rather than `heading`.
