### ISSUE TITLE
disable default paragraph tags

### ISSUE THREAD

**Issue by sidbelbase** [lepture/mistune#253]
`For instance, **this** is an example.` gets converted into `<p>For instance, <strong>this</strong> is an example.</p>`, can we customize this into only `For instance, <strong>this</strong> is an example.`

```py
from mistune import markdown as mistune_markdown

@core.app_template_filter('markdown')
def markthatdown(any_text, **options):
    return Markup(mistune_markdown(any_text))
```

I'm using mistune in flask and it is already wrapped inside `<p></p>` so with the default also being enabled creates a nested `<p>` tags breaking UI. 

Can we customize or disable `<p></p>` tags?

**Comment by yujiri8** [comment]
I don't know how satisfying this is but you can subclass the HTMLRenderer and override its `paragraph` method or something.

**Comment by lepture** [comment]
@yujiri8 is correct.

**Comment by sidbelbase** [comment]
There's no `HTMLRenderer` subclass in `v1` I guess?

I had to use 
`from flask import Markup`
for that :(

**Comment by lepture** [comment]
In v1, it is `mistune.Renderer`.

**Comment by sidbelbase** [comment]
does it render like markup or do I need to use `Markup` from flask?

**Comment by lepture** [comment]
@sidbelbase that is depending on your usage. You can use it without `Markup` at first.
