### ISSUE TITLE
In 2.0 how do we get hard_wrap=False or parse_block_html=True

### ISSUE THREAD

**Issue by samtstern** [lepture/mistune#256]
I'm looking to upgrade from 0.8.4 to 2.0 and I used to invoke mistune like this:

```py
    renderer = mistune.Renderer(escape=False, hard_wrap=False, parse_block_html=True)
    markdown = mistune.Markdown(renderer=renderer)
```

Now I see that `escape` is still an option but the others are gone:

```py
    markdown = mistune.create_markdown(escape=False)
```

How do I get similar behavior to what I had in 0.8.4?

**Comment by lepture** [comment]
@samtstern It can be done with a custom inline parser. Since it is a common feature, I've added it back onto InlineParser. You can learn how to use it with the tests in `test_misc`.

For `parse_block_html`, we don't have this feature anymore. You can only subclass `BlockParser` and rewrite the `parse_block_html` function to get your goal.

**Comment by samtstern** [comment]
@lepture thank you for the quick response and the new support in `InlineParser`!  I'm not quite familiar enough with the library to be able to subclass `BlockParser` but maybe after I use it some more I'll understand and maybe even submit a Pull Request with the feature.

**Comment by lepture** [comment]
@samtstern I think it is `parse_block_html=True` is already supported with `escape=False`. But there are some tricks:

For example:

```
<div>

## h2 text

</div>
```

Will be converted into:

```
<div>
<h2>h2 text</h2>
</div>
```

But below won't:

```
<div>
## h2 text
</div>
```

**Comment by luggie** [comment]
@lepture I not very familiar with this package either but also looking for an upgrade from 0.8.4. to 2.0
before I used mistune 
```
html = mistune.markdown(text, escape=False, hard_wrap=True)
html = ...
```
How would be the equivalent for this in mistunde 2 (or even 3?)
