### ISSUE TITLE
Mistune Plugin regex flag pattern inconsistent

### ISSUE THREAD

**Issue by MC42** [lepture/mistune#257]
I'm attempting to write a plugin for mistune to generate a HTML "item", even if the detect string span multiple lines.  Springing from the example for the wiki plugin on the [advanced guide](https://mistune.readthedocs.io/en/latest/advanced.html), I changed the regex, the render, etc.  It all works very well, except for detecting across multiple lines. 

Despite using a regex pattern that includes newlines, mistune does not render the desired text properly. I thought I had poorly formatted the regex, but testing it directly with re.findall() (and on regex builder sites)  suggests it is in fact _correctly_ designed, leading me to ask for help here.  

![image](https://user-images.githubusercontent.com/6531081/99712049-87eb9880-2a70-11eb-80f9-6050895e2bd6.png)

Gist is [here](https://gist.github.com/MC42/b72139be4127b652e5c01075e68dd910) for my test case, any help would be appreciated.  Can I change a flag in mistune to use the global regex flag in some way / match more than one / match per instance or is that implied?  

Any help would be appreciated.

**Comment by lepture** [comment]
```
BB

This is a test of a multiline bluebox.

### Inner text markdown!

ENDBB
```

From my understanding, this should be a block rule. You can learn how to register a block rule with table and footnotes plugin.

**Comment by MC42** [comment]
You're absolutely correct - a friend helped me through it and got a version working with the block rules and an ast.  Sorry and thank you!
