### ISSUE TITLE
Q: Why don't the parsers output the AST?

### ISSUE THREAD

**Issue by akvadrako** [lepture/mistune#262]
I found mistune recently because it seems fast and simple and mostly like it. Yet there is an aspect of the design which I don't understand; it would help me like it more if the docs explained it or it was simplified.

Basically it seems like the parsers output an "almost AST", like `('link', url, children, title)` and the AST renderer does trivial transforms to `{ 'type': 'link', 'link': link,  'children': children, 'title': title }`. This means that adding a new node type requires writing one of these trivial methods and potentially the two AST-like formats could have surprising differences.

So my question is: why don't parsers output AST nodes directly and have the HTML renderer consume them?

**Comment by lepture** [comment]
It is designed for performance. `tuple` cost less than `dict`.

**Comment by lepture** [comment]
Yes, HTML is priority. Because most users are using it to produce HTML.

I think you can create another AstRender to output tuples.

**Comment by lepture** [comment]
The parser output AST by default in `v3` now, please check `v3` branch.
