### ISSUE TITLE
Introduce and use typing

### ISSUE THREAD

**Issue by Spenhouet** [lepture/mistune#265]
Your project currently does not make use of typing: https://docs.python.org/3/library/typing.html

Everyone working with your library and / or implementing new plugins and renderers will have a hard time figuring out what you data structure looks like, what methods and parameters are expected, ...

In my experience using typing also vastly improves code quality and reduces mistakes.

Please consider to use typing for your v2 remake.

**Comment by Spenhouet** [comment]
@lepture I found this comment for yours [here](https://github.com/lepture/mistune/pull/242#discussion_r439378671):
> please don't add type hint. Mistune is compatible with Python 2.7

I very much disagree with that.
Python 2 is no longer supported since 01.01.2020. That's now already one year. You are going to release a new major version of mistune. This is absolutely the right time to break python 2.7 support and only support python 3+.

**Comment by lepture** [comment]
Yeah, it is time to support typing now.

**Comment by lepture** [comment]
added in v3.
