### ISSUE TITLE
[Question] Can i and how do I use mistune as lexer/parser for markdown table as syntax for toy language?

### ISSUE THREAD

**Issue by simkimsia** [lepture/mistune#272]
I wonder if there's a way to write a toy programming language (perhaps using Python?) that processes syntax such as markdown tables.

Basically instead of
```python
a_dict = {"a": 1, "b": 2}
```
This toy language would accomplish the equivalent with
```markdown
begin_table as a_dict
| Key     | Value |
| ------- | ----- |
| "a"     | 1     |
| "b"     | 2     |
end_table
```
Something like that. How would I go about writing a toy programming language for that kind of syntax?

I did find a [link](https://blog.usejournal.com/writing-your-own-programming-language-and-compiler-with-python-a468970ae6df) that explains how to write own language and compiler using Python, but it seems to assume treat the processing of character by character ASCII text as immutable. I wonder how possible it is to process an entire markdown table like the above?

And can I use mistune to accomplish the above?

**Comment by lepture** [comment]
I don't think so.
