### ISSUE TITLE
Mistune 2.0.0 release?

### ISSUE THREAD

**Issue by maxking** [lepture/mistune#284]
Hi,

I have been testing markdown rendering in our archiver for GNU Mailman project, Hyperkitty for some time now using the alpha/rc version of mistune 2.0. While it works okay in our test environments, i was hoping that released stable versions rely on the non-pre-release dependencies.

I was wondering if you had any plans for the 2.0 release for mistune? There seems to be no issues or PRs marked with the 2.0 milestone at the moment.

**Comment by P-EB** [comment]
Hi @lepture 

Do you think you will have some time to consider whether or not mistune 2.0.0 could be released?

Cheers,
PEB

**Comment by lepture** [comment]
@P-EB there are still documentation missing.

**Comment by P-EB** [comment]
> @P-EB there are still documentation missing.

Ack, is there something I could do to help?

**Comment by P-EB** [comment]
@lepture sure! I'll give it a look and offer a MR!

**Comment by P-EB** [comment]
@lepture done, see PR #289

**Comment by lepture** [comment]
released.

**Comment by P-EB** [comment]
<3
