### ISSUE TITLE
Support for malformed headings

### ISSUE THREAD

**Issue by sapristi** [lepture/mistune#285]
Hello, 
I'm using mistune to parse reddit comments, and it seems that reddit is a bit permissive regarding heading: the space between the `#`'s and the heading title is not necessary.

Would you be interested in supporting that kind of malformed markdown in mistune ? (although i've looked a bit, and this does not seem very straightforward to parameterize).
I'm mostly opening the issue for future reference and to let people know ;)

**Comment by lepture** [comment]
You can subclass `BlockParser` and update `AXT_HEADING`, use your own `BlockParser` with `create_markdown`.
