### ISSUE TITLE
Attribute 'BlockGrammar' not found during sphinx-build run   

### ISSUE THREAD

**Issue by oldfoz** [lepture/mistune#291]
During running Sphinx v4.3.1 I got the following:

Exception occurred:
  File "C:\slb\code\flowback_tools\.tox\docs\lib\site-packages\m2r2.py", line 83, in <module>
    class RestBlockGrammar(mistune.BlockGrammar):
AttributeError: module 'mistune' has no attribute 'BlockGrammar'

The log file attached
[sphinx-err-d5tghc9k.log](https://github.com/lepture/mistune/files/7674092/sphinx-err-d5tghc9k.log)

For the previous version of mistune such an issue has not raised.

Thanks and best regards!

**Comment by mahendrapaipuri** [comment]
@oldfoz The new mistune (>2) has different API and it breaks `m2r2` that still relies on `mistune<2`. A workaround is to constraint `mistune<2` in your builds.
