### ISSUE TITLE
2.0.x regression in multi-line list entry handling

### ISSUE THREAD

**Issue by mr-c** [lepture/mistune#296]
mistune 0.8.x would allow multi-line entries in lists, even if the next line wasn't indented; this seems to have gone away.

Is there a way to restore this behaviour?

Our use case is rendering the official versions of standards documents that have already been released. So changing the source markdown is problematic for us.

``` Python
import mistune

markdown_text="""
* Using virtual machines or operating system containers to manage the runtime
(except as described in [DockerRequirement](CommandLineTool.html#DockerRequirement)).
* Using remote or distributed file systems to manage input and output files.
"""

_old_mistune = int(mistune.__version__.split(".", maxsplit=1)[0]) < 2

if _old_mistune:
    print(mistune.markdown(markdown_text))
else:
    print(mistune.html(markdown_text))
```

Diff of the results (0.8.4 versus 2.0.2)
``` diff
2,3c2,5
< <li>Using virtual machines or operating system containers to manage the runtime
< (except as described in <a href="CommandLineTool.html#DockerRequirement">DockerRequirement</a>).</li>
---
> <li>Using virtual machines or operating system containers to manage the runtime</li>
> </ul>
> <p>(except as described in <a href="CommandLineTool.html#DockerRequirement">DockerRequirement</a>).</p>
> <ul>
```

**Comment by mr-c** [comment]
According to https://daringfireball.net/projects/markdown/syntax#list and https://spec.commonmark.org/0.30/#example-290 hanging indents are not required in Markdown

**Comment by lepture** [comment]
I'm working on a new version now. It would be easier to fix this issue in the new version.

**Comment by lepture** [comment]
@mr-c please check `v3` branch, it should be fixed in v3.

**Comment by lepture** [comment]
It is fixed in v3.
