### ISSUE TITLE
How can I use the code of mistune contrib in mistune?

### ISSUE THREAD

**Issue by fanrongqitiancai** [lepture/mistune#297]
I hope mistune supports mathjax. I don't know how to put math in mistune contrib Py added to mistune, how do I need to write code? Is it a plug-in or a new renderer? How do I get mistune to use multiple renderers? Such as HTML renderer and math renderer? I read math in mistune contrib Py code, class mathrenderer (mistune. Renderer) is not found.

**Comment by lepture** [comment]
v3 supports mathjax now. please check `v3` branch.
