### ISSUE TITLE
Comments does not work

### ISSUE THREAD

**Issue by mauro-balades** [lepture/mistune#299]
Even if I put `<!--` as a prefix and `-->` as a suffix, mistune does not count it as a comment.

**Comment by lepture** [comment]
Here is my test:

```python
>>> text = 'hello <!-- **world** -->'
>>> mistune.html(text)
'<p>hello <!-- **world** --></p>\n'
```

It works well. Can you provide an example to reproduce your issue?

**Comment by mauro-balades** [comment]
just a normal comment...
```md
# hello

<!-- comment -->
```

it renders as:

```hmtl
<h1>hello<h1>

<p>&lt;!-- hello --&gt;</p>

**Comment by lepture** [comment]
@mauro-balades oh, it is because you have turned `escape` on. With `escape=True`, any HTML will be escaped.

**Comment by mauro-balades** [comment]
> @mauro-balades oh, it is because you have turned `escape` on. With `escape=True`, any HTML will be escaped.

Hmmm... So, how can I have scape enabled + comments?

**Comment by lepture** [comment]
@mauro-balades for your case, I'd suggest customizing `block_html` method on renderer:

```py
def block_html(self, html):
    if html.startswith('<!--') and html.endswith('-->'):
        return html
    return escape(html)
```

**Comment by mauro-balades** [comment]
👍🏽
