### ISSUE TITLE
Support python-markdown admonition extension

### ISSUE THREAD

**Issue by cas--** [lepture/mistune#300]
I noticed when converting some Material MkDocs pages with [md2cf](https://github.com/iamjackg/md2cf) that admonitions were not converted:

```
!!! cite "A great man once said ..."
```

It seems that mistune has it's own [admonition directive](https://mistune.readthedocs.io/en/latest/directives.html#admonitions) but would it be possible to add support for python-markdown [admonition extension](https://python-markdown.github.io/extensions/admonition/) as a plugin?

Material MkDocs has a list of [supported types](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types) with a fallback to `note` if unrecognised.

**Comment by cas--** [comment]
Closing since this as just read that this is Mistune Flavored Markdown (MFM) so not likely to add this if already has own admonition directive

**Comment by lepture** [comment]
@cas-- you can actually create a plugin yourself.
