### ISSUE TITLE
Hyperlinks in angle brackets with an @ character get turned into mailto: links

### ISSUE THREAD

**Issue by HermanMartinus** [lepture/mistune#302]
Mastodon profile URLs contain an @, so for example

<https://mastodon.social/@mastodon>

Becomes a link to mailto:https://mastodon.social/@mastodon

**Comment by lepture** [comment]
@HermanMartinus what's the version are you using?

I just tried with master code:

```
>>> mistune.html('<https://mastodon.social/@mastodon>')
'<p><a href="https://mastodon.social/@mastodon">https://mastodon.social/@mastodon</a></p>\n'
```
