### ISSUE TITLE
Function to render section of AST to HTML?

### ISSUE THREAD

**Issue by Mark-L6n** [lepture/mistune#303]
Is there a way to render a section of an AST to HTML (or back to the original Markdown)?
Motivation: not need to parse all of an AST.  For example, in a Heading node, the text for the heading is contained in a list of children. Instead of parsing that list of children, I'd rather just render it as HTML (or failing that, get back the original markdown).  Is there a function to do this?

**Comment by lepture** [comment]
From your request, it seems that you only wish to get the block level AST. You can use the `BlockParser`:

```python
block = BlockParser()

tokens = block.parse(s, {})
```

**Comment by Mark-L6n** [comment]
Thanks for the quick response.  The table plugin is not used by default -- is there a way to specify that it be used?

**Comment by Mark-L6n** [comment]
Reading lepture/mistune/issues/158, I inserted `'table'` into `list_rules`, but it still does not recognize tables.
`block.list_rules.insert(4, 'table')` resulting in:
`['newline', 'thematic_break', 'fenced_code', 'indent_code', 'table', 'block_quote', 'block_html', 'list_start', 'axt_heading', 'setex_heading', 'def_link']`

**Comment by lepture** [comment]
@Mark-L6n please check https://github.com/lepture/mistune/blob/master/mistune/plugins/table.py#L149-L152
