### ISSUE TITLE
Unexpected regex matching behaviour

### ISSUE THREAD

**Issue by Newbytee** [lepture/mistune#304]
I'm trying to port an app ([Moment](https://gitlab.com/mx-moment/moment)) from Mistune 0.8.4 to Mistune 2.0, but I'm struggling with figuring out what's going here: 

```python
import mistune

def parse_colour(inline, m, state):
    colour = m.group(1)
    text = m.group(2)
    return "colour", colour, text


def render_html_colour(colour, text):
    return f'<span data-mx-color="{colour}">{text}</span>'


def plugin_matrix(md):
    colour = (
        r"^<(.+?)>"          # capture the colour in `<colour>`
        r"\((.+?)"           # capture text in `(text`
        r"(?<!\\)(?:\\\\)*"  # ignore the next `)` if it's \escaped
        r"\)"                # finish on a `)`
    )

    md.inline.register_rule("colour", colour, parse_colour)
    md.inline.rules.append("colour")

    if md.renderer.NAME == "html":
        md.renderer.register("colour", render_html_colour)


markdown_to_html = mistune.create_markdown(
    hard_wrap = True,
    escape = True,
    renderer = "html",
    plugins = [plugin_matrix],
)

markdown = """
<#ff0000>(red text!)
"""

print(markdown_to_html(markdown))
```

This works fine for turning `<#ff0000>(red text!)` into `<span data-mx-color="#ff0000">red text!</span>`. However, `<red>(red text!)` turns into `&lt;red&gt;(red text!)`, which is not what I would have expected given that my regular expression should match this too and turn it into `<span data-mx-color="red">red text!</span>`. This regex matches both patterns just fine when I test it in a Python shell by importing `re`, and this pattern also worked fine in Mistune 0.8.4 as far as I can tell: https://gitlab.com/mx-moment/moment/-/blob/2a1a96e762e7e7c6dce13a7caa8b34f7222230d7/src/backend/html_markdown.py#L35-40

What gives? Am I missing something? I've tried looking into Mistune's source code to see if I can figure out what's going on, but I don't think I understand Python well enough.

**Comment by lepture** [comment]
@Newbytee Hi, from my debug, `<red>` has matched `inline_html`. In this case, you can put this rule before `inline_html`.

```
md.inline.rules.insert(1, "colour")
```

BTW, I'm designing v3 now. The parser would be better, hopefully I can release an alpha version in next week. I'm using Mistune heavily in [Typlog](https://typlog.com/).

**Comment by Newbytee** [comment]
> @Newbytee Hi, from my debug, <red> has matched inline_html. In this case, you can put this rule before inline_html.

> md.inline.rules.insert(1, "colour")

Nice, thank you! That did the trick. However, after adding this the ) is retained it seems? So, it becomes for instance `<span data-mx-color="#ff0000">red text!)</span>`. Do you have any idea why this might be? I really don't see how this change could result in that.

> BTW, I'm designing v3 now. The parser would be better, hopefully I can release an alpha version in next week. I'm using Mistune heavily in [Typlog](https://typlog.com/).

Nice! Could you make sure that this one can be installed in parallel with Mistune v2? Mistune has become a bit of an issue in some Linux distributions as 0.8 and 2.0 can't be installed in parallel and some programs use 0.8 whereas others use 2.0.

**Comment by lepture** [comment]
@Newbytee I'm using `v3` code now. It would be easier to fix this issue in v3.

**Comment by Newbytee** [comment]
Is this closed as completed because v3 is out or because it was fixed in v2?

**Comment by lepture** [comment]
Because it is fixed in v3. It is hard to fix it in v2.
