### ISSUE TITLE
Version 2.0.3 bold formatting seems broken

### ISSUE THREAD

**Issue by brettkromkamp** [lepture/mistune#312]
The following Markdown renders correctly in 2.0.2 (see first screenshot):
`This is a **test** note. So... just to be absolutely clear: this is a note for the purpose of **testing**.`

![Screenshot from 2022-07-14 17-46-41](https://user-images.githubusercontent.com/160078/179023686-a96ada36-3424-4633-892b-dacd5cb3c80a.png)

Nonetheless, in 2.0.3 it renders differently (see second screenshot below):

![Screenshot from 2022-07-14 17-47-41](https://user-images.githubusercontent.com/160078/179023777-34dbaa3f-447c-4bb6-8e27-ace0b58da094.png)

**Comment by lepture** [comment]
Thanks for the report, it has been fixed in 2.0.4. I've just made a new release.
