### ISSUE TITLE
abbr plugin error?

### ISSUE THREAD

**Issue by Neutree** [lepture/mistune#317]
![image](https://user-images.githubusercontent.com/8625829/190687929-bab6add7-780f-4bf8-98bf-ea10a1fe2e59.png)

https://github.com/lepture/mistune/blob/1264a1c954396fa31304bfac39588381f015a5d8/mistune/plugins/abbr.py#L56-L63

maybe here `def_abbr` and should the same as `abbr`? I run my code local no error, but on github action error occurs
> full log here https://github.com/teedoc/teedoc/actions/runs/3069280480/jobs/4957741255

**Comment by AntheSevenants** [comment]
Do not install the library from the pip repository, as this will download and install v2. To use the newer plugins, you have to pull v3 directly from GitHub:
```bash
pip install git+https://github.com/lepture/mistune
```

**Comment by lepture** [comment]
We have v3 rc releases in PyPI.
