### ISSUE TITLE
I created some plugins and directive, should I create a PR

### ISSUE THREAD

**Issue by Neutree** [lepture/mistune#318]
## directives

* tabset: https://github.com/teedoc/teedoc/blob/main/plugins/teedoc-plugin-markdown-parser/teedoc_plugin_markdown_parser/plugin_tabset.py
![image](https://user-images.githubusercontent.com/8625829/190688970-419d508f-42f8-431b-ae0e-549d126e29d0.png)
```markdown

(note that a blank line is required here)
.. tabset::tab title (optional)
    :id: tabset1

    ## Label one

    Content 1, you can use Markdown syntax
    ```kotlin
      fun main() {
          println("Hello World")
      }
    ```

    ## Label two

    Content 2, you can use Markdown syntax
    ```java
      public class Main {
          public static void main(String[] args) {
              System.out.println("Hello World");
          }
      }
    ```
```

* details: https://github.com/teedoc/teedoc/blob/main/plugins/teedoc-plugin-markdown-parser/teedoc_plugin_markdown_parser/plugin_details.py

![image](https://user-images.githubusercontent.com/8625829/190689099-714e15bb-7f66-459d-b3c2-e5dc81624924.png)
```markdown
.. details::Title, click to expand

    Content 1, you can use Markdown syntax
    ```kotlin
      fun main() {
          println("Hello World")
      }
    ```

.. details:: title, expanded by default
    :open:true

    Content 1, you can use Markdown syntax
    ```kotlin
      fun main() {
          println("Hello World")
      }
    ```
```

## plugins

* superscript: https://github.com/teedoc/teedoc/blob/main/plugins/teedoc-plugin-markdown-parser/teedoc_plugin_markdown_parser/plugin_superscript.py
```markdown
y = x^2^
```

* subscript: https://github.com/teedoc/teedoc/blob/main/plugins/teedoc-plugin-markdown-parser/teedoc_plugin_markdown_parser/plugin_subscript.py
```markdown
Water: H~2~O
```

**Comment by lepture** [comment]
@Neutree from v3, we have a community file to list 3rd party plugins. You can add your plugin here: https://mistune.lepture.com/en/latest/community.html

But in v3, we have built-in plugins for superscript and subscript. Please see: https://mistune.lepture.com/en/latest/plugins.html

I've just released v3.0.0rc1, you can upgrade teedoc to mistune v3 for the powerful plugins. It is quite stable now, I'm using v3 in production in Typlog.
