### ISSUE TITLE
Custom Plugin - Why does detecting [[xxx]] work but [xxx] not?

### ISSUE THREAD

**Issue by michaelrampl** [lepture/mistune#320]
See the following Example:

The pattern to detect an object of type `[[xxx]]`
```
PATTERN_XXX_DOUBLE = (
    r'\[\['
    r'xxx'
    r'\]\]'
)
```
will be recognized, but the other one for `[xxx]`
```
PATTERN_XXX_SINGLE = (
    r'\['
    r'xxx'
    r'\]'
)
```
won't. Why is this and how can this be avoided/fixed?

**Comment by lepture** [comment]
Because `[xx]` is link referrer. It is already defined in parsing links.

**Comment by michaelrampl** [comment]
Is there somehow a way to overwrite this behavior?

**Comment by lepture** [comment]
Put the rule before link rule.
