### ISSUE TITLE
Ampersand characters in image source are escaped (v2.0.4)

### ISSUE THREAD

**Issue by acidtv** [lepture/mistune#321]
Example:
```python
import mistune                                                          
content = "![description](https://foo.com/?a=1&b=2)"                    
markdown = mistune.create_markdown(escape=False)                        
markdown(content)
# '<p><img src="https://foo.com/?a=1&amp;b=2" alt="description" /></p>\n' 
```

This causes problems loading the image in some cases.

I think this is caused by `escape_url` using `html.escape`. According to the docs  (https://docs.python.org/3/library/html.html) `html.escape` escapes ampersands, and I don't think that should happen for urls.

**Comment by lepture** [comment]
It is commonmark compatible, please check:

<https://spec.commonmark.org/dingus/?text=!%5Bdescription%5D(https%3A%2F%2Ffoo.com%2F%3Fa%3D1%26b%3D2)>

**Comment by acidtv** [comment]
My bad, this was a bug in our custom mistune renderer.

Thanks for checking!
