### ISSUE TITLE
type hints

### ISSUE THREAD

**Issue by mr-c** [lepture/mistune#329]
Would you like a donation of inline type hints? I can send a PR to apply @fmigneault  type hints from https://github.com/common-workflow-language/schema_salad/commit/47332275ae04540a4b71ccfa0ff160edbef01496#diff-b6fac26c3692bb3b814467d88fe4b15140151671dc85689c3d2eb7385e95afd8 to as inline type hints , if you would release a new 2.x with it

**Comment by lepture** [comment]
@mr-c sure, I can accept type hints for 2.x
