### ISSUE TITLE
Nested blocks inside a directive

### ISSUE THREAD

**Issue by ahopkins** [lepture/mistune#343]
Are nested directives supported? I am trying to create a custom directive to add some columns. But, I would like to also have other directives and block level items. It seems that only inline parsing is happening inside of the directive. Is there something that I need to enable? Is this supported?

**Comment by ahopkins** [comment]
Figured it out.

```python
class Column(DirectivePlugin):
    def parse(
        self, block: BlockParser, m: Match, state: BlockState
    ) -> dict[str, Any]:
        info = m.groupdict()

        new_state = block.state_cls()
        new_state.process(info["text"].strip())
        block.parse(new_state)

        return {
			...,
            "children": new_state.tokens,
        }
```

**Comment by lepture** [comment]
@ahopkins Hi, if you have already fixed it, can you close this issue?

**Comment by ahopkins** [comment]
All good, thanks.
