### ISSUE TITLE
LaTeX equation should not be parsed when it is enclosed in span tags

### ISSUE THREAD

**Issue by rossant** [lepture/mistune#38]
```python
import mistune

md = mistune.Markdown(parse_html=False)
print(md.render('''

<div>$$x_y x_{y}$$</div>

<span>$$x_y x_{y}$$</span>

'''))

# Prints:
# <div>$$x_y x_{y}$$</div>
# <p><span>$$x<em>y x</em>{y}$$</span></p>
```

The LaTeX equation is parsed when it is in the span, not when it is in the div. I think it should not be parsed since it is within HTML tags.

**Comment by bollwyvl** [comment]
Other example of embedded html breaking things: appears to be the issue on https://github.com/jupyter/nbviewer/issues/458

**Comment by lepture** [comment]
@rossant @bollwyvl fixed this issue with https://github.com/lepture/mistune/commit/19a8c393272748855ada902a750e3cde467ac6bc

**Comment by bollwyvl** [comment]
Fantastic! I'll take a look at it in nbviewer downstream, and report back.
These pesky angle brackets!
