### ISSUE TITLE
Change self-closing tags to void elements

### ISSUE THREAD

**Issue by stuartmaxwell** [lepture/mistune#397]
Hi there - I couldn't find any reports of this in the issues, so hopefully I'm not repeating a previous issue.

Is there any interest to change the behaviour of Mistune to produce [void elements](https://developer.mozilla.org/en-US/docs/Glossary/Void_element) instead of [self-closing tags](https://developer.mozilla.org/en-US/docs/Glossary/Void_element#self-closing_tags)? Examples of these are: `<hr>`, `<br>`, or `<img ...>` - these are currently rendered as `<hr />`, `<br />`, or `<img ... />` which is no longer considered to be valid HTML.

From what I can tell, the code that produces this is in `mistune/src/mistune/renderers/html.py` in the following three places:

- image: <https://github.com/lepture/mistune/blob/0772c78bc0a62771768278263ef740345f58c0f0/src/mistune/renderers/html.py#L85-L91>
- linebreak: <https://github.com/lepture/mistune/blob/0772c78bc0a62771768278263ef740345f58c0f0/src/mistune/renderers/html.py#L96-L97>
- thematic_break: <https://github.com/lepture/mistune/blob/0772c78bc0a62771768278263ef740345f58c0f0/src/mistune/renderers/html.py#L121-L122>

I would be happy to work on this myself and create a pull request, I just wanted to check in with you first to see if you would be willing to accept this?

Cheers - Stuart.

**Comment by stuartmaxwell** [comment]
I should note, that I'm already over-riding those three methods in my own custom renderer and appears to work fine. But I see there will be other changes in the code as well as fixing up the tests.

In my custom renderer:

```python
    def image(self, text: str, url: str, title: Optional[str] = None) -> str:
        src = self.safe_url(url)
        alt = escape_text(striptags(text))
        s = '<img src="' + src + '" alt="' + alt + '"'
        if title:
            s += ' title="' + safe_entity(title) + '"'
        return s + ">"

    def thematic_break(self) -> str:
        return "<hr>\n"

    def linebreak(self) -> str:
        return "<br>\n"
```

**Comment by lepture** [comment]
Mistune is using test cases from CommonMark https://spec.commonmark.org/0.31.2/ and CommonMark is using self-closing tags.

**Comment by stuartmaxwell** [comment]
OK - I'll close this issue. I raised a discussion on the CommonMark forums but have had no response yet.

**Comment by lepture** [comment]
For now, you can use custom renderer.
