### ISSUE TITLE
wheel package format

### ISSUE THREAD

**Issue by stonebig** [lepture/mistune#40]
Would it be possible to have a "universal" wheel on pypi ?

**Comment by lepture** [comment]
@stonebig do you mean a pure python version universal wheel?

**Comment by stonebig** [comment]
yes, something like 
````
python setup.py sdist bdist_wheel --universal 
````

**Comment by lepture** [comment]
@stonebig wheel is available. https://pypi.python.org/pypi/mistune

**Comment by stonebig** [comment]
thanks
