### ISSUE TITLE
Problem with integrating Emoji support

### ISSUE THREAD

**Issue by sh4nks** [lepture/mistune#42]
Hey!

First of all, thanks for your work!

I am trying to integrate mistune into my flask extension (https://github.com/sh4nks/flask-emoji) but I have some troubles to get it working. The standalone renderer (without mistune) works fine.

The code for the integration: https://github.com/sh4nks/flask-emoji/blob/master/flask_emoji/ext/mistune_renderer.py
I just followed your the example and studied the source a bit (which unfortunately didn't help)
and this is how I initialize it: https://github.com/sh4nks/flask-emoji/blob/master/flask_emoji/__init__.py#L189-L199

This is the output when I use it (it just renders the first appearance of an emoji and ignores the ones):
```
Single Emoji: ':smile:'
<p><img src="emoji/smile.png" alt="smile" title="smile"></p>

Cats and Dogs: 'It's raining :cat:s and :dog:s'
<p>It's raining :cat:s and :dog:s</p>

Multiple in one line: ':smile: :smiley:'
<p><img src="emoji/smile.png" alt="smile" title="smile"> :smiley:</p>

Other: '![test](test.png) ![test2](test2.png)'
<p><img src="test.png" alt="test"> <img src="test2.png" alt="test2"></p>
```

Could you help me to get it working? :wink: 
Thanks!

**Comment by lepture** [comment]
@sh4nks You don't need a lexer to do this job. Hacking in the paragraph renderer is much easier. Use a regex pattern to deal with text in the paragraph.

**Comment by sh4nks** [comment]
Thaanks! It works :smile:  I have been trying for a few hours already haha
