### ISSUE TITLE
@phoikoi use the renderer feature

### ISSUE THREAD

**Issue by lepture** [lepture/mistune#49]
Hi @phoikoi 

I found that you were modifying mistune source to add some weird things. It can be easy done with a custom renderer. Checkout this part: https://github.com/lepture/mistune#renderer

All you need is subclass of Renderer and overwrite the `image` function. Please don't modify the source code like this https://github.com/phoikoi/mistune/commit/38f296b400387885493bee296b2962b9f356d846

**Comment by tomspur** [comment]
Hi @lepture,

where do I modify the sources? All I did so far with mistune is [reviewing](https://bugzilla.redhat.com/show_bug.cgi?id=1170664) it to get it added to Fedora.

**Comment by lepture** [comment]
@tomspur sorry. I mean @phoikoi it is the GitHub autocompletion bug.
