### ISSUE TITLE
Version 0.6

### ISSUE THREAD

**Issue by lepture** [lepture/mistune#50]
- [x] don't render text in inline html: https://github.com/lepture/mistune/issues/38
- [x] line-breaks break italic/bold https://github.com/lepture/mistune/issues/48

**Comment by lepture** [comment]
@takluyver FYI. https://github.com/lepture/mistune/commit/19a8c393272748855ada902a750e3cde467ac6bc will change behavior on inline html tags.

```
<span>**hello**</span>
```

Before this commit, it will be rendered as:

```
<span><strong>hello</strong></span>
```

After this commit, it will be:

```
<span>**hello**</span>
```

**Comment by takluyver** [comment]
Thanks for letting us know - I think that makes sense. Pinging @minrk as well so he's aware of this.

**Comment by lepture** [comment]
ping @takluyver @minrk 

I am going to release it this weekend.

**Comment by minrk** [comment]
Thanks for letting us know.

**Comment by lepture** [comment]
It's 0.6 now.
