### ISSUE TITLE
moving from misaka - header anchors

### ISSUE THREAD

**Issue by techtonik** [lepture/mistune#57]
I am trying to figure out is mistune can be a replacement for this use case:
```
html = misaka.html( md,
    misaka.EXT_STRIKETHROUGH | misaka.EXT_AUTOLINK | misaka.EXT_FENCED_CODE | \
    misaka.EXT_TABLES,
    misaka.HTML_SMARTYPANTS | misaka.HTML_TOC )
```
It looks like HTML_TOC is not supported, and I am not sure about misaka.HTML_SMARTYPANTS

For those moving from misaka, it will be handy to have a table with mapped methods/properties.

**Comment by lepture** [comment]
@techtonik There is no TOC in mistune, you need build the TOC with renderer. Smartypants can be done in `text` renderer with some replacement.

**Comment by lepture** [comment]
@techtonik I've implemented a TOC renderer here: https://github.com/lepture/mistune-contrib/blob/master/mistune_contrib/toc.py

And here is the test case: https://github.com/lepture/mistune-contrib/blob/master/tests/test_toc.py

**Comment by techtonik** [comment]
@lepture thanks. That will surely become handy once I make http://inside.gratipay.com running on new Aspen https://github.com/gratipay/inside.gratipay.com/pull/263#issuecomment-113509846

**Comment by lepture** [comment]
@techtonik Thanks, the TOC renderer is not finished yet, there are many cases I haven't tested. For example:

How to parse it into TOC?

```
## level 2
# level 1
```

**Comment by techtonik** [comment]
@lepture and how does misaka threats it?

GitHub does render lists with invalid nesting as something correct. So maybe do not care about it until somebody comes up with a use case. 

 * level 2
* level 1

**Comment by lepture** [comment]
Here is the misaka output:

```html
<ul>
<li>
<a href="#toc_0">level 2</a>
</li>
</ul>
</li>
<li>
<a href="#toc_1">level 1</a>
```

**Comment by techtonik** [comment]
So, make it a valid HTML with empty top level for the first element, no?

**Comment by techtonik** [comment]
@lepture why not to provide an already mixed in version?
