### ISSUE TITLE
false detection of inline comment

### ISSUE THREAD

**Issue by jlec** [lepture/mistune#58]
any email address starting with something from _inline_tag won't get recognized

e.g.

```
<ape@foo.bar>
<b@foo.bar>
```

**Comment by lepture** [comment]
@jlec Yes, it won't in the version 0.6. see https://github.com/lepture/mistune/issues/38

I've just fixed this with an option of **parse_inline_html=True**. You can try the code in master branch.

**Comment by jlec** [comment]
Perfect, that works.

**Comment by lepture** [comment]
0.7 released.

**Comment by jlec** [comment]
I am still hitting this bug with 0.7.1

**Comment by lepture** [comment]
Add a test

**Comment by jlec** [comment]
```python
from __future__ import print_function

import mistune

markdown = mistune.Markdown()

print(markdown.render("<a@foo.bar>"))
print(markdown.render("<b@foo.bar>"))
print(markdown.render("<a-b@foo.bar>"))
```
gives
```html
<p><a href="mailto:a@foo.bar">a@foo.bar</a></p>

<p><a href="mailto:b@foo.bar">b@foo.bar</a></p>

<p><a-b@foo.bar></p>
```
