### ISSUE TITLE
mistune .6 breaks HTML rendering of Jupyter notebooks

### ISSUE THREAD

**Issue by groutr** [lepture/mistune#60]
We had a user notice an issue with mistune .6.  They were able to confirm that downgrading to mistune 0.5.1 solved the problem.  Posting here so it can be addressed.
https://github.com/ContinuumIO/anaconda-issues/issues/364

**Comment by lepture** [comment]
@groutr It is a known change. 

refer links:

1. https://github.com/lepture/mistune/issues/38
1. https://github.com/jupyter/nbviewer/issues/458
1. https://github.com/jupyter/nbconvert/issues/45
1. https://github.com/lepture/mistune/issues/51
1. https://github.com/lepture/mistune/issues/58

It is changed in https://github.com/lepture/mistune/issues/50

**Comment by lepture** [comment]
The plan is to roll a new version with options `parse_inline_html` and `parse_block_html`. https://github.com/lepture/mistune/blob/master/CHANGES.rst#version-07

**Comment by lepture** [comment]
0.7 released.
