### ISSUE TITLE
mistune 0.7

### ISSUE THREAD

**Issue by lepture** [lepture/mistune#61]
The next release contains these changes:

https://github.com/lepture/mistune/blob/master/CHANGES.rst#version-07

1. Add two options to fix breaking changes in version 0.6: parse_inline_html and parse_block_html
2. Change option escape default value to False for security reason

@takluyver @minrk @apenwarr @oberstet

compare view: https://github.com/lepture/mistune/compare/v0.6...3c953752ecbe6db5bfe7a9158f91a19c895acbfc

It will be released in the next week, maybe Jul. 10.

**Comment by takluyver** [comment]
@lepture should that be that the default value of escape was changed to *True*? That's what 0f5313c52c4beaee623d05e62eb05d10c7cbf281 did.

**Comment by lepture** [comment]
I think you don't need to worry, since you are using the custom renderer, you won't use the markdown function.

**Comment by takluyver** [comment]
I'm not especially worried, it just looked like there's a typo in the
release notes.

**Comment by lepture** [comment]
@takluyver ah. Thanks.

**Comment by lepture** [comment]
ping @minrk @apenwarr @oberstet

It will be released this week.

**Comment by lepture** [comment]
released.
