### ISSUE TITLE
problem in escaping in 0.6

### ISSUE THREAD

**Issue by minrk** [lepture/mistune#63]
There seems to be a problem in mistune ≥ 0.6 escaping HTML when it shouldn't. For instance, the literal html `<h1>text</h1>` is passed through unmodified, exactly as it should be. However, the exact same html snippet is escaped if there is any other text outside the tag, instead of being left alone.

Test case:

```python
from mistune import Markdown
md = Markdown(escape=False)
print(md.render("""<h1>not escaped</h1>"""))
print(md.render("""<h1>escaped</h1>
text"""))
```

Has output:

```
<h1>not escaped</h1>
<p>&lt;h1&gt;escaped&lt;/h1&gt;
text</p>
```

**Comment by lepture** [comment]
Fixed in the master branch.
