### ISSUE TITLE
Create a Jinja2 extension to be used with Mistune

### ISSUE THREAD

**Issue by lipis** [lepture/mistune#65]
Something like this one https://github.com/danielchatfield/jinja2_markdown but for Mistune:

``` markdown
{% markdown %}
  Hello World
  ---------------
  - Foo
  - Bar
{% endmarkdown %}
```

and it could also work as a filter (but not really needed for Markdown as the above case is much better):

```
{{some_text|markdown}}
```

If someone has some extra time it would be super cool to have :)

**Comment by lepture** [comment]
Actually you don't need an extension. A filter can be called as a block::

```
{% filter markdown %}
something here
{% endfilter %}
```

Like this: https://github.com/lepture/lepture.com/blob/master/index.html#L74

**Comment by lepture** [comment]
Ah, I see. The extension strips the leading whitespace.

**Comment by lipis** [comment]
I think the stripping is nice.. but not sure if is really necessary on the other hand.. obviously the code looks better if you don't have to start from column 1 all the time.

**Comment by lepture** [comment]
Close it now. Not a part of this project.
