### ISSUE TITLE
Auto-line breaks

### ISSUE THREAD

**Issue by rudyryk** [lepture/mistune#68]
Didn't found, is there a simple auto-line breaks support?

**Comment by lepture** [comment]
@rudyryk what do you mean by "auto line" ? Can you give me an example?

**Comment by rudyryk** [comment]
I mean converting every new line to <br> tag :) That's not by Markdown initial standard, but this is very common tweak, i.e. GitHub and Tubmlr have it.

**Comment by lepture** [comment]
> hard_wrap: if set to True, it will has GFM line breaks feature.

**Comment by rudyryk** [comment]
That's awesome! Didn't notice that, sorry!

Not sure if that should be highlighted more in docs or I just should read docs closer :) But I've read it several times and finally dived into source code :)

I'd suggest expand description for `hard_wrap` argument a little bit like "all new lines will be replaced with `\<br /\>` tag".

Thank you!

**Comment by lepture** [comment]
Added to docs.
