### ISSUE TITLE
block_code is not invoked 

### ISSUE THREAD

**Issue by Dorothy00** [lepture/mistune#69]
when highlight code  I override the fuction block_code(self,code,lang),but find that the render always return &lt;pre&gt;&lt;code&gt;sss&lt;/code&gt;&lt;/pre&gt; such code, it means the block_code don't work. I have tested pigments's highlight function is right.

**Comment by lepture** [comment]
I can't understand your question.

**Comment by Dorothy00** [comment]
I mean use this example:
class HighlightRenderer(mistune.Renderer):
    def block_code(self, code, lang):
        if not lang:
            return '\n&lt;pre&gt;&lt;code&gt;%s&lt;/code&gt;&lt;/pre&gt;\n' % \
                mistune.escape(code)
        lexer = get_lexer_by_name(lang, stripall=True)
        formatter = HtmlFormatter()
        return highlight(code, lexer, formatter)
the code  which read from a file will not be highlight, which only output this kind of code format:
&lt;h1&gt;third_post&lt;/h1&gt;\n\n&lt;pre&gt;&lt;code&gt;#include &lt;iostream&gt;\nint main(){\n    return 0;\n}&lt;/code&gt;&lt;/pre&gt;\n
I mean no css style is attached.

**Comment by lepture** [comment]
Execute this:

```python
import mistune
from pygments import highlight
from pygments.lexers import get_lexer_by_name
from pygments.formatters import HtmlFormatter

class HighlightRenderer(mistune.Renderer):
    def block_code(self, code, lang):
        if not lang:
            return '\n<pre><code>%s</code></pre>\n' % \
                mistune.escape(code)
        lexer = get_lexer_by_name(lang, stripall=True)
        formatter = HtmlFormatter()
        return highlight(code, lexer, formatter)

renderer = HighlightRenderer()
markdown = mistune.Markdown(renderer=renderer)
print(markdown('```python\nassert 1 == 1\n```'))
```

The `lang` is designed for **fenced code** block. A fenced code looks like:

    ```python
    print('hello')
    ```

**Comment by seniorcandy** [comment]
there is a AttributeError: 'Markdown' object has no attribute 'output_footnote_end'
after I add the HighlightRenderer renderer

**Comment by lepture** [comment]
@seniorcandy please open another issue with a minimal test case.
