### ISSUE TITLE
escape=False doesn't work with parse_html=True

### ISSUE THREAD

**Issue by tdivis** [lepture/mistune#70]
When I call `mistune.markdown()` function with `escape=False`, it correctly doesn't escape the HTML elements, but when I add `parse_html=True`, the HTML elements specified in the input are escaped even though they shouldn't be (at least the HTML from parsed markdown is not escaped), see below:
```
In [1]: import mistune

In [2]: mistune.markdown('<div>**foo**</div>', escape=False)
Out[2]: '<div>**foo**</div>'

In [3]: mistune.markdown('<div>**foo**</div>', escape=False, parse_html=True)
Out[3]: '&lt;div&gt;<strong>foo</strong>&lt;/div&gt;'
```

**Comment by lepture** [comment]
version 0.7 has no `parse_html` option. Version 0.7 has resolved this bug.

**Comment by lepture** [comment]
duplicated with https://github.com/lepture/mistune/issues/63

**Comment by lepture** [comment]
Seems a little different.

**Comment by tdivis** [comment]
> version 0.7 has no parse_html option. Version 0.7 has resolved this bug.

OK, I'm sorry, I was on current master, but I didn't noticed `mistune.so` file, which was used in this case and was created with an older version, after deleting it, it works fine (when I change `parse_html` to `parse_block_html`).

Thanks and once again sorry for invalid ticket.
