### ISSUE TITLE
MathJax working example ?

### ISSUE THREAD

**Issue by Depado** [lepture/mistune#73]
Hi,
It has been a few days since I started using Mistune, mainly because I saw a MathJax support that Misaka had not (and as a pure python implementation, would allow to do more things). I'm kind of stuck right now though. I had a look in the mistune-contrib repository, but couldn't find a clear explanation about what was going on. 

My question is :
Is there a simple (or not simple at all) example of MathJax support using Mistune ? 

(Appart from that, Mistune works fine, great job :+1: )

**Comment by f-koehler** [comment]
Hi,
in the [mistune-contrib](https://github.com/lepture/mistune-contrib/blob/master/mistune_contrib/math.py) example @lepture shows how you can write mixins for the inline and block lexer as well as for the renderer. These are very straightforward to use.

I am currently hacking mistune myself. I follow the path of how the guys from IPython have done it [here](https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/markdown_mistune.py). They create a subclass and extend the rules of the grammar.

Of course you have to change the regexes to fit your MathJax configuration. I found that both ways work just fine except for the inline math. The regex does not seem to get matched and I did not yet have had the time to investigate what the reason might be. I opened #72 but lepture has not replied yet.

I would be interested if you find a solution.

**Comment by Depado** [comment]
Hi, 
I personnaly don't find those examples straightforward to use. I guess I lack of python skills sometimes haha. I'll give that a try. Looks like @lepture answered your issues with the regular expressions you should use in #72. I would be interested in having your working code if that isn't a problem, because I still can't figure out what I'm doing exactly there haha

**Comment by Depado** [comment]
Alright I got it working using the link you sent about IPython. Thanks a lot @f-koehler ! :)

**Comment by nournia** [comment]
Hi,
I've used IPython example and it worked for me.

But this feature disables `hard_wrap` which needs different `InlineGrammar` rules. Here is one simple example:

    >>> markdown = MarkdownWithMath(renderer=Renderer(), hard_wrap=True)
    >>> markdown.render('this **foo** \nis me')
    '<p>this <strong>foo</strong> \nis me</p>\n'

The correct result is: 

    >>> markdown = Markdown(renderer=Renderer(), hard_wrap=True)
    >>> markdown.render('this **foo** \nis me')
    '<p>this <strong>foo</strong><br>\nis me</p>\n'
