### ISSUE TITLE
Documentation on hard_wrap is misleading

### ISSUE THREAD

**Issue by F30** [lepture/mistune#77]
The README says that all options should be specified when creating the Renderer and only mentions the possibility of passing them to `mistune.Markdown` as a shortcut.

However, `hard_wrap` is not handled by the Renderer and must be specified for the Markdown object. Despite that, even the example contains `mistune.Renderer(hard_wrap=True)`. As far as I can tell, the same applies for `parse_block_html` and `parse_inline_html`, but I haven't looked at those in detail.

**Comment by lepture** [comment]
I decided to use the options on renderer. Fixed in the master branch now.
