### ISSUE TITLE
Various Extension System Problems

### ISSUE THREAD

**Issue by mitsuhiko** [lepture/mistune#79]
I just looked at how the grammar is extended and in it's current form it's not really usable.  There are a few problems with the way the inline lexer is supposed to modified alone:
- right now the example modifies `default_rules` which is a class attribute and as such shared across all other lexers as well.
- because the `text` rule is greedy it needs to be modified whenever another rule is inserted but it is impossible for a plugin to do so because it cannot now which sequences indicate the start of a rule.  The current example only works by chance.

I think the current design does not really suit itself to extension well but I'm not sure how to fix it without breaking what's already there.

**Comment by lepture** [comment]
It was first ported from marked.js. This is why it follows the design of marked. I've noticed it is hard to be  extended https://github.com/lepture/mistune/issues/62

**Comment by mitsuhiko** [comment]
Yeah. It's quite disappointing :( If you want some more concrete advise on how to do it I can probably outline some general suggestions.

**Comment by lepture** [comment]
@mitsuhiko That would be helpful. I am not good at writing parsers.

**Comment by mitsuhiko** [comment]
Because none of the pocoo servers are backed up. So if they go broken then whatever comes out of the repos is what the websites will look like.

**Comment by lepture** [comment]
@mitsuhiko wrong repo

**Comment by mitsuhiko** [comment]
Goddammit :) Do you have some text messenger? Easier than issue trackers for this sort of stuff.

**Comment by lepture** [comment]
@mitsuhiko How about  https://telegram.me/lepture

**Comment by mitsuhiko** [comment]
I investigated the re module a bit for that purpose and discovered how the undocumented `re.Scanner` is implemented.  A modified version of it is perfect for mistune: https://gist.github.com/mitsuhiko/153c29b778068d3798fc

**Comment by nitely** [comment]
@lepture @mitsuhiko Any progress on this?

I've been toying around with @mitsuhiko's [scanner][0] and got a basic parser working (no extensions yet). The only issue so far is backreferences seem to not work, so it's probably not possible to avoid breaking changes in mistune.

[0]: https://github.com/mitsuhiko/python-regex-scanner

**Comment by lepture** [comment]
@nitely not yet.

**Comment by nitely** [comment]
Hey @lepture ,

I'm don't know how advanced this re-implementation is, but I wanted to share what I have so far[0], since *I'm not planning in ever releasing it as a library*. It might serve you as inspiration.

Every element is implemented as an extension, so it should be highly extensible. The text is parsed, then an AST is generated, then the AST is rendered as HTML. A different render can be easily implemented as well.

I've written it a while ago, but IIRC, it's able to correctly parse [daring fireball](https://daringfireball.net/projects/markdown/) examples and docs. Benchmarks shows it's as fast as mistune.

[0]: https://gist.github.com/nitely/9fe34f64cd300aaa92af731f5634ce8b

**Comment by lepture** [comment]
@nitely Thanks for sharing. Scanner is different in Python 2 and Python 3, that's why I'm hesitated to implement it in scanner. Currently my focus is on other projects, so that this will be hold on for a while.

**Comment by nitely** [comment]
> Thanks for sharing.

NP 😺 

> Scanner is different in Python 2 and Python 3, that's why I'm hesitated to implement it in scanner.

mmh it is. But still works in py2 and py3 (the code I shared is for py3). I made a PR for fixing the original @mitsuhiko code https://github.com/mitsuhiko/python-regex-scanner/pull/3 .

> Currently my focus is on other projects, so that this will be hold on for a while.

Yeah, no problem. mistune is actually good enough for me at its current state.

**Comment by lepture** [comment]
v2 is ready now.
