### ISSUE TITLE
Math expressions

### ISSUE THREAD

**Issue by nournia** [lepture/mistune#8]
Usage of math expressions in Markdown text is quite common. I've found this PR chjj/marked#180 in `marked` which brings this feature. Main issue with current implementation occurs in cases like this:

```
$ A_{i} + B_{i} $
```

That inner part of `$`s must not be rendered as a normal piece of Markdown text. Actually, mentioned PR is not merged yet but I think supporting this expressions only needs exclusion of `$`s content. For example, output of this simple case:

```
$ A_{i} $
```

Is completely compatible with `MathJax` which renders that as its equivalent expression.

**Comment by martinosorb** [comment]
I believe this issue is again there in mistune v2. Is there a way to avoid parsing markdown within `$$` equation blocks?
