### ISSUE TITLE
renderer link not escaped

### ISSUE THREAD

**Issue by zTrix** [lepture/mistune#80]
```
>>> markdown('**blah** [asdfasdf](blasdfh">)')
'<p><strong>blah</strong> <a href="blasdfh">">asdfasdf</a></p>\n'
```

github rendered:

**blah** [asdfasdf](blasdfh">) afd

**Comment by qll** [comment]
Just for the sake of completeness, here is an actual XSS vector using JavaScript (avoiding the parantheses by using templates)

```python
>>> mistune.markdown('[text]("><script>alert`1`</script>)')
'<p><a href=""><script>alert`1`</script>">text</a></p>\n'
```

**Comment by qll** [comment]
@nitely found out that the same problem appears in images, too. This could be moved to an own issue or be collected in here, but that's your call.

```python
>>> mistune.markdown('![text]("><script>alert`1`</script>)')
'<p><img src=""><script>alert`1`</script>" alt="text"></p>\n'
```

**Comment by Kingwl** [comment]
it's very helpful to me!
