### ISSUE TITLE
Content of block_html should be parsed by BlockLexer

### ISSUE THREAD

**Issue by tdivis** [lepture/mistune#82]
Even with `parse_block_html=True`, content of the HTML block is parsed only by InlineLexer, even though it's typical that block HTML elements like `<div>` contains other block elements (i.e. heading):

```
>>> print markdown('''
<div id="special-part">

## Some special heading

Some **super** paragraph.

</div>''', parse_block_html=True, parse_inline_html=True, escape=False
)
<div id="special-part">

## Some special heading

Some <strong>super</strong> paragraph.</div>
```

So emphasis was parsed (as it is inline) but heading was not parsed.

Maybe this has the same solution as #81 (some kind of nested block parsing needed)?

**Comment by lepture** [comment]
Yeah. I think the two are the same issue.

**Comment by lepture** [comment]
please try v2.0.0a1
