### ISSUE TITLE
Version 0.7.1 broke inline base64; images 

### ISSUE THREAD

**Issue by rochacbruno** [lepture/mistune#83]
When included html tags with src=base64 it works in  versions before 0.7, with 0.7 it broke

**Comment by lepture** [comment]
Could you add a test case?

**Comment by lepture** [comment]
It is still broke with the master branch?

**Comment by nkanaev** [comment]
yes, it is. below are the results:

    >>> import mistune
    >>> mistune.__version__
    '0.7.3'
    >>> mistune.markdown('![test](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)')
    '<p><img src="" alt="test"></p>\n'

and:

    >>> import mistune
    >>> mistune.__version__
    '0.6'
    >>> mistune.markdown('![test] (data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==)')
    '<p><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="test"></p>\n'


however, there are some concerns about using `data` as url links (for ex. discussed [here](https://github.com/github/markup/issues/270)).

**Comment by nkanaev** [comment]
I can suggest 2 solutions:

1. leave it as it is 

to workaround this, developers'll have to write raw img:

    import mistune
    mistune.markdown('<img src="data:image/png;base64,XXX" />', escape=False)

or override image rendering to bypass security checks:

    import mistune

    class CustomRenderer(mistune.Renderer):
        def image(self, src, title, text):
            text = mistune.escape(text, quote=True)
            if title:
                title = mistune.escape(title, quote=True)
                html = '<img src="%s" alt="%s" title="%s"' % (src, text, title)
            else:
                html = '<img src="%s" alt="%s"' % (src, text)
            if self.options.get('use_xhtml'):
                return '%s />' % html
            return '%s>' % html

    mistune.markdown('![test](data:image/png;base64,XXX)', renderer=CustomRenderer())



2. check `data` for images:

maybe allow 'image/png', 'image/jpg' and 'image/gif' only

**Comment by lepture** [comment]
715046fe4b5f3642b24edc7fdd62ba8915228498 this commit fixed it.

**Comment by mitsuhiko** [comment]
@lepture why is data html blacklisted?
