### ISSUE TITLE
Markdown Validation / Data Extraction?

### ISSUE THREAD

**Issue by danfrankj** [lepture/mistune#84]
I'm looking to validate markdown files input by users and wondering if this package might help. I've read through the Renderer() docs and while this isn't the main use case I'm wondering if you have any advice on a way to do validation and data extraction. 

For example, I'd like to check that there is a line that looks like this

**Title:** this is the title

And be able to extract the title. 

I could always parse to html and then use something like BeautifulSoup but that seemed a bit hacky too.

Thoughts?

**Comment by lepture** [comment]
You can use the lexer part. But it is not documented well.
