### ISSUE TITLE
Break out HTML output assumption

### ISSUE THREAD

**Issue by irskep** [lepture/mistune#89]
Mistune is really, really close to being useful as a generalized Markdown parser. But it's not quite there yet. What I really need is a complete parse tree, not an HTML string.

I'm going to fork this temporarily. If I find a clean way to get what I need, I'll send a PR. The alternative for me is to write my own Markdown parser, which is not an appealing idea. :-)

## Problem 1: lexer outputs HTML

https://github.com/lepture/mistune/blob/master/mistune.py#L593

Shouldn't this be the renderer's job?

## Problem 2: hard-coded list of inline, block, pre tags

I have a pretty unusual use case, but it shouldn't be too hard to support: I want to specify a custom list of HTML tags.

**Comment by irskep** [comment]
I just realized you can substitute the lexer, which is pretty nice. So maybe this isn't strictly a problem. It's just awkward; there's a reason there's typically an AST or parse tree intermediate step in programs like these.

**Comment by irskep** [comment]
FWIW I just decided to go use [CommonMark](https://github.com/jgm/CommonMark) instead, since it has a more conventional (and general) API.

**Comment by lepture** [comment]
> Problem 1: lexer outputs HTML

The source itself is HTML.
