### ISSUE TITLE
How can I escape characters like ``` ?

### ISSUE THREAD

**Issue by bameda** [lepture/mistune#91]
I want to scape characters, for example three ` because I want to create a page to describe the markdown language, something like this

![image](https://cloud.githubusercontent.com/assets/877218/13784424/7aac41f0-eacf-11e5-8fed-c82888527fdc.png)

is this possible?

**Comment by lepture** [comment]
Indent it with 4 spaces:

![image](https://cloud.githubusercontent.com/assets/290496/13798546/096e297c-eb5b-11e5-81f0-0d30f00cf028.png)

**Comment by bameda** [comment]
Cool, thanks!!
