### ISSUE TITLE
possibly wrong "loose item"?

### ISSUE THREAD

**Issue by Xunius** [lepture/mistune#92]
Hi dev,

I'm testing out this module and comparing the output with that from markdown2, and I noticed some differences that I guess markdown2 gets it right. Here is the code snippet I used followed by the outputs:
## code:

```
import mistune
import markdown2

text='''this is test _**bold test**_ of markdown ** parser
test.

- item1;
- item2;
- item3.

1. num1;
2. num2;
3. num3.
'''

markdown = mistune.Markdown()
out=markdown(text)
out2=markdown2.markdown(text)

print text
print '\n'
print out
print '\n'
print out2

```
## Output:

```
this is test _**bold test**_ of markdown ** parser
test.

- item1;
- item2;
- item3.

1. num1;
2. num2;
3. num3.



<p>this is test <em><strong>bold test</strong></em> of markdown ** parser
test.</p>
<ul>
<li>item1;</li>
<li>item2;</li>
<li><p>item3.</p>
</li>
<li><p>num1;</p>
</li>
<li>num2;</li>
<li>num3.</li>
</ul>



<p>this is test <em><strong>bold test</strong></em> of markdown ** parser
test.</p>

<ul>
<li>item1;</li>
<li>item2;</li>
<li>item3.</li>
</ul>

<ol>
<li>num1;</li>
<li>num2;</li>
<li>num3.</li>
</ol>

```

Seems that the "loose item" logic leads to the difference. And the 2nd numbered list is not recognized correctly.

**Comment by Zopieux** [comment]
I was just hit by that bug trying to implement a custom renderer. I do not understand what is the definition of a *loose item*, so I can't suggest a fix. Any idea @lepture?

**Comment by lepture** [comment]
Fixed by https://github.com/lepture/mistune/pull/152
