### ISSUE TITLE
Math Support already included?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [lepture/mistune#93]
I was going to add some code I found online to my project, in order to support math mode of tex in my markdown files. When I reloaded the website I am building, to my big surprise, MathJax was already working its magic and the formulars rendered nicely. All I did was including the MathJax JS and config like this:

`<script type="text/x-mathjax-config">
			MathJax.Hub.Config({
				tex2jax: {inlineMath: [['$','$']]}
			});
		</script>
		<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>`

Is math now supported without any further coding?

I installed mistune from PyPi, using the Anaconda Python distribution. The mistune library is at version 0.7.2.

This is not really an issue, but maybe you could state that there is math support in mistune already in a feature list on the github page, if it is really so :+1: : )

**Comment by lepture** [comment]
It is not built-in. Here is a hint: https://github.com/lepture/mistune-contrib

**Comment by ZelphirKaltstahl** [comment]
What I am saying is, that for some reason it works out of the box for me. No need for any contrib repo stuff. It already works and that's what I think is surprising.

**Comment by andya9** [comment]
This is because mathjax can be fed latex, asciimath or mathml; so if you just call the script, it will do everything client-side

**Comment by andya9** [comment]
*Probably* mistune just ignores the $$ strings, so they are sent raw to the html; those $$ strings are native to mathjax: it’s them that tell mathjax "here’s there’s math, process it"

**Comment by lepture** [comment]
Got it. I'll close this issue.
