### ISSUE TITLE
Support for styled spans

### ISSUE THREAD

**Issue by vsajip** [lepture/mistune#94]
I needed to support styled spans (like `code` but with user-defined styles). As mentioned in issue #79, this is hard to do via the current extension mechanisms. I have therefore implemented it in a branch, by making small changes (a couple of changes to patterns in `InlineGrammar`, and updated `output_code` and `codespan` methods) - around 10 lines in total. It works like this:

`` `code` `` is handled as before, but `` :fizz buzz:`foo` `` is rendered to `<span class="fizz buzz">foo</span>`.

I've updated the test fixtures too, and all tests pass. Would you be interested in a patch / PR for this?

**Comment by lepture** [comment]
I'd like to have a look at the patch.

**Comment by vsajip** [comment]
Okay, but I've realised there's a more general approach which works without changes to the core. I now use `[span contents](custom-link)` and handle it in my `Renderer` subclass. This has the additional benefit of allowing markdown inside the `[span contents]` :-)

Just for reference, [here is the patch](https://gist.github.com/vsajip/80ef81a46c7235d8470d6724be46cbbe).

**Comment by lepture** [comment]
This is not a common grammar, better put a snippet in the contrib repo.
