### ISSUE TITLE
Strikethrough processing is faulty

### ISSUE THREAD

**Issue by vsajip** [lepture/mistune#95]
```
>>> mistune.Markdown()('~~ABC~~')  # OK
'<p><del>ABC</del></p>\n'
>>> mistune.Markdown()('~~A~~')  # Not OK
'<p>~~A~~</p>\n'
>>> mistune.Markdown()('~~A~~ B ~~C~~')  # Also not OK
'<p><del>A~~ B ~~C</del></p>\n'
>>>
```

**Comment by lepture** [comment]
@vsajip Thanks for your feedback. It should be fixed by https://github.com/lepture/mistune/commit/9c15c0f8d76e9d0fca8b2f41de214e43ee16c732

**Comment by vsajip** [comment]
I'm not sure your change is the ideal fix. For example, you now allow a space between the `~~` and the word, which AFAIK is not as per previous behaviour - and I'm not sure it conforms to other Markdown implementations. I used `~~(?=\S)([\s\S]*?\S)~~`, which I think is better - it just makes the inner search non-greedy.

**Comment by lepture** [comment]
@vsajip a pr is welcome
